defmodule Opsonde.Repo.Migrations.InventoryImports do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  and reviewed to create referenced tables before their dependants.
  """

  use Ecto.Migration

  def up do
    create table(:inventory_imports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source_type, :text, null: false
      add :source, :text, null: false
      add :status, :text, null: false
      add :snapshot_status, :text
      add :source_version, :text
      add :content_digest, :text, null: false
      add :row_count, :bigint, null: false
      add :error_count, :bigint, null: false
      add :revision, :bigint, null: false, default: 1
      add :applied_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :provider_id,
          references(:providers,
            column: :id,
            name: "inventory_imports_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :created_by_id,
          references(:users,
            column: :id,
            name: "inventory_imports_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:inventory_imports, [:provider_id])
    create index(:inventory_imports, [:created_by_id])

    create table(:inventory_import_rows, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false
      add :disposition, :text, null: false
      add :identity_source, :text, null: false
      add :identity_kind, :text, null: false
      add :identity_value, :text, null: false
      add :candidate, :map, null: false, default: %{}
      add :provenance, :map, null: false, default: %{}
      add :errors, {:array, :text}, null: false, default: []
      add :target_revision, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inventory_import_id,
          references(:inventory_imports,
            column: :id,
            name: "inventory_import_rows_inventory_import_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :target_id,
          references(:targets,
            column: :id,
            name: "inventory_import_rows_target_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:inventory_import_rows, [:inventory_import_id, :position],
             name: "inventory_import_rows_unique_import_position_index"
           )

    create index(:inventory_import_rows, [:inventory_import_id])
    create index(:inventory_import_rows, [:target_id])
  end

  def down do
    drop table(:inventory_import_rows)
    drop table(:inventory_imports)
  end
end
