defmodule Opsonde.Repo.Migrations.SplitRecoveryBaseline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cases) do
      add :recovery_baseline_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:cases) do
      remove :recovery_baseline_at
    end
  end
end
