defmodule Opsonde.Repo.Migrations.CaseLifecycle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  and reviewed to create referenced tables before their dependants.
  """

  use Ecto.Migration

  def up do
    create table(:cases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :trigger_kind, :text, null: false
      add :source, :text, null: false
      add :source_ref, :text, null: false
      add :title, :text, null: false
      add :severity, :text, null: false
      add :alert_state, :text, null: false
      add :status, :text, null: false
      add :initial_context, :map, null: false, default: %{}
      add :authority_setting_revision, :bigint, null: false
      add :authority_mode, :text, null: false
      add :max_elapsed_seconds, :bigint, null: false
      add :max_resolver_turns, :bigint, null: false
      add :max_target_requests, :bigint, null: false
      add :max_effects, :bigint, null: false
      add :max_related_targets, :bigint, null: false
      add :max_ai_usage_units, :bigint, null: false
      add :max_no_progress_turns, :bigint, null: false
      add :cancel_requested, :boolean, null: false, default: false
      add :stop_reason, :text
      add :pending_intent, :map, null: false, default: %{}
      add :required_human_input, :text
      add :source_recovered_at, :utc_datetime_usec
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :authority_setting_id,
          references(:authority_settings,
            column: :id,
            name: "cases_authority_setting_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :initial_target_id,
          references(:targets,
            column: :id,
            name: "cases_initial_target_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :current_owner_id,
          references(:users,
            column: :id,
            name: "cases_current_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:cases, [:trigger_kind, :source, :source_ref],
             name: "cases_unique_trigger_index"
           )

    create index(:cases, [:authority_setting_id])
    create index(:cases, [:initial_target_id])
    create index(:cases, [:current_owner_id])

    create table(:resolution_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :generation, :bigint, null: false
      add :active, :boolean, null: false
      add :status, :text, null: false
      add :authority_mode, :text, null: false
      add :max_elapsed_seconds, :bigint, null: false
      add :max_resolver_turns, :bigint, null: false
      add :max_target_requests, :bigint, null: false
      add :max_effects, :bigint, null: false
      add :max_related_targets, :bigint, null: false
      add :max_ai_usage_units, :bigint, null: false
      add :max_no_progress_turns, :bigint, null: false
      add :turn_count, :bigint, null: false, default: 0
      add :target_request_count, :bigint, null: false, default: 0
      add :effect_count, :bigint, null: false, default: 0
      add :related_target_count, :bigint, null: false, default: 0
      add :ai_usage_units, :bigint, null: false, default: 0
      add :no_progress_turns, :bigint, null: false, default: 0
      add :started_at, :utc_datetime_usec, null: false
      add :deadline_at, :utc_datetime_usec, null: false
      add :ended_at, :utc_datetime_usec
      add :resume_reason, :text
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "resolution_runs_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :resumed_by_id,
          references(:users,
            column: :id,
            name: "resolution_runs_resumed_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:resolution_runs, [:case_id, :generation],
             name: "resolution_runs_unique_generation_index"
           )

    create unique_index(:resolution_runs, [:case_id],
             name: "resolution_runs_one_active_run_index",
             where: "(active = TRUE)"
           )

    create index(:resolution_runs, [:resumed_by_id])

    create table(:case_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_type, :text, null: false
      add :idempotency_key, :text
      add :data, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "case_events_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :resolution_run_id,
          references(:resolution_runs,
            column: :id,
            name: "case_events_resolution_run_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :actor_id,
          references(:users,
            column: :id,
            name: "case_events_actor_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:case_events, [:case_id, :idempotency_key],
             name: "case_events_unique_idempotency_index"
           )

    create index(:case_events, [:case_id])
    create index(:case_events, [:resolution_run_id])
    create index(:case_events, [:actor_id])
  end

  def down do
    drop table(:case_events)
    drop table(:resolution_runs)
    drop table(:cases)
  end
end
