defmodule Opsonde.Repo.Migrations.CaseResolutionTimestamp do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cases) do
      add :resolved_at, :utc_datetime_usec
      remove :source_recovered_at
    end
  end

  def down do
    alter table(:cases) do
      add :source_recovered_at, :utc_datetime_usec
      remove :resolved_at
    end
  end
end
