defmodule Opsonde.Repo.Migrations.NativeSignalConditions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:conditions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :occurrence, :bigint, null: false
      add :predicate, :text, null: false
      add :subject_key, :text, null: false
      add :subject_ref, :map, null: false, default: %{}
      add :state, :text, null: false
      add :first_fired_at, :utc_datetime_usec, null: false
      add :current_occurred_at, :utc_datetime_usec, null: false
      add :current_source_sequence, :text
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :signal_correlation_id,
          references(:signal_correlations,
            column: :id,
            name: "conditions_signal_correlation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:conditions, [:signal_correlation_id, :occurrence],
             name: "conditions_unique_occurrence_index"
           )

    alter table(:conditions) do
      add :target_id,
          references(:targets,
            column: :id,
            name: "conditions_target_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:conditions, [:signal_correlation_id],
             name: "conditions_one_firing_occurrence",
             unique: true,
             where: "state = 'firing'"
           )

    create index(:conditions, [:target_id])

    alter table(:signal_events) do
      add :condition_id,
          references(:conditions,
            column: :id,
            name: "signal_events_condition_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:signal_events, [:condition_id])
  end

  def down do
    drop_if_exists index(:signal_events, [:condition_id])

    drop constraint(:signal_events, "signal_events_condition_id_fkey")

    alter table(:signal_events) do
      remove :condition_id
    end

    drop_if_exists index(:conditions, [:target_id])

    drop_if_exists index(:conditions, [:signal_correlation_id],
                     name: "conditions_one_firing_occurrence"
                   )

    drop constraint(:conditions, "conditions_target_id_fkey")

    drop constraint(:conditions, "conditions_signal_correlation_id_fkey")

    alter table(:conditions) do
      remove :target_id
    end

    drop_if_exists unique_index(:conditions, [:signal_correlation_id, :occurrence],
                     name: "conditions_unique_occurrence_index"
                   )

    drop table(:conditions)
  end
end
