defmodule Opsonde.Repo.Migrations.RemoveCaseAlertState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cases) do
      remove :alert_state
    end
  end

  def down do
    alter table(:cases) do
      add :alert_state, :text, null: false
    end
  end
end
