defmodule Opsonde.Repo.Migrations.CaseReportLanguage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cases) do
      add :report_language, :text, null: false, default: "en"
    end
  end

  def down do
    alter table(:cases) do
      remove :report_language
    end
  end
end
