defmodule Opsonde.Repo.Migrations.ConditionSubjectScopedOccurrences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:conditions, [:signal_correlation_id, :subject_key, :predicate],
             name: "conditions_one_firing_subject",
             unique: true,
             where: "state = 'firing'"
           )

    drop_if_exists index(:conditions, [:signal_correlation_id],
                     name: "conditions_one_firing_occurrence"
                   )
  end

  def down do
    create index(:conditions, [:signal_correlation_id],
             name: "conditions_one_firing_occurrence",
             unique: true,
             where: "state = 'firing'"
           )

    drop_if_exists index(:conditions, [:signal_correlation_id, :subject_key, :predicate],
                     name: "conditions_one_firing_subject"
                   )
  end
end
