defmodule Opsonde.Repo.Migrations.AddBmcOperations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:bmc_operations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text, null: false
      add :request_kind, :text, null: false
      add :protocol_request, :map, null: false
      add :input_schema, :map, null: false
      add :output_schema, :map, null: false
      add :verification_schema, :map
      add :active, :boolean, null: false, default: true
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :access_method_id,
          references(:access_methods,
            column: :id,
            name: "bmc_operations_access_method_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:bmc_operations, [:access_method_id, :name],
             name: "bmc_operations_unique_method_name_index"
           )

    create index(:bmc_operations, [:access_method_id])
  end

  def down do
    drop_if_exists index(:bmc_operations, [:access_method_id])

    drop constraint(:bmc_operations, "bmc_operations_access_method_id_fkey")

    drop_if_exists unique_index(:bmc_operations, [:access_method_id, :name],
                     name: "bmc_operations_unique_method_name_index"
                   )

    drop table(:bmc_operations)
  end
end
