defmodule Opsonde.Repo.Migrations.AiInvocationDelivery do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ai_invocations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :status, :text, null: false
      add :idempotency_key, :text, null: false
      add :request_digest, :text, null: false
      add :provider_revision, :bigint, null: false
      add :assignment_revision, :bigint, null: false
      add :selection_source, :text, null: false
      add :reserved_units, :bigint, null: false
      add :input_tokens, :bigint, null: false, default: 0
      add :output_tokens, :bigint, null: false, default: 0
      add :category, :text
      add :result_digest, :text
      add :dispatch_started_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "ai_invocations_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:ai_invocations, [:idempotency_key],
             name: "ai_invocations_unique_idempotency_index"
           )

    alter table(:ai_invocations) do
      add :resolution_run_id,
          references(:resolution_runs,
            column: :id,
            name: "ai_invocations_resolution_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :turn_id,
          references(:turns,
            column: :id,
            name: "ai_invocations_turn_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :proposal_id,
          references(:proposals,
            column: :id,
            name: "ai_invocations_proposal_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :provider_id,
          references(:providers,
            column: :id,
            name: "ai_invocations_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :assignment_id,
          references(:ai_usage_role_assignments,
            column: :id,
            name: "ai_invocations_assignment_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:ai_invocations, [:case_id])

    create index(:ai_invocations, [:resolution_run_id])

    create index(:ai_invocations, [:turn_id])

    create index(:ai_invocations, [:proposal_id])
  end

  def down do
    drop_if_exists index(:ai_invocations, [:proposal_id])

    drop_if_exists index(:ai_invocations, [:turn_id])

    drop_if_exists index(:ai_invocations, [:resolution_run_id])

    drop_if_exists index(:ai_invocations, [:case_id])

    drop constraint(:ai_invocations, "ai_invocations_assignment_id_fkey")

    drop constraint(:ai_invocations, "ai_invocations_provider_id_fkey")

    drop constraint(:ai_invocations, "ai_invocations_proposal_id_fkey")

    drop constraint(:ai_invocations, "ai_invocations_turn_id_fkey")

    drop constraint(:ai_invocations, "ai_invocations_resolution_run_id_fkey")

    drop constraint(:ai_invocations, "ai_invocations_case_id_fkey")

    alter table(:ai_invocations) do
      remove :assignment_id
      remove :provider_id
      remove :proposal_id
      remove :turn_id
      remove :resolution_run_id
    end

    drop_if_exists unique_index(:ai_invocations, [:idempotency_key],
                     name: "ai_invocations_unique_idempotency_index"
                   )

    drop table(:ai_invocations)
  end
end
