defmodule Opsonde.Repo.Migrations.RetireAiProvider do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:providers, [:name], name: "providers_unique_name_index")

    alter table(:providers) do
      add :retired_at, :utc_datetime_usec
    end

    create unique_index(:providers, [:name],
             name: "providers_unique_name_index",
             where: "(retired_at IS NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:providers, [:name], name: "providers_unique_name_index")

    alter table(:providers) do
      remove :retired_at
    end

    create unique_index(:providers, [:name], name: "providers_unique_name_index")
  end
end
