defmodule Opsonde.Repo.Migrations.RecurringSignalCases do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:cases, [:trigger_kind, :source, :source_ref],
                     name: "cases_unique_trigger_index"
                   )

    create unique_index(:cases, [:trigger_kind, :source, :source_ref],
             name: "cases_unique_trigger_index",
             where: "(trigger_kind <> 'signal')"
           )

    create unique_index(:cases, [:trigger_kind, :source, :source_ref],
             name: "cases_one_active_signal_trigger_index",
             where: "(trigger_kind = 'signal' AND status IN ('running', 'needs_attention'))"
           )
  end

  def down do
    drop_if_exists unique_index(:cases, [:trigger_kind, :source, :source_ref],
                     name: "cases_one_active_signal_trigger_index"
                   )

    drop_if_exists unique_index(:cases, [:trigger_kind, :source, :source_ref],
                     name: "cases_unique_trigger_index"
                   )

    create unique_index(:cases, [:trigger_kind, :source, :source_ref],
             name: "cases_unique_trigger_index"
           )
  end
end
