defmodule Opsonde.Repo.Migrations.OperationDelivery do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:operations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false
      add :case_generation, :bigint, null: false
      add :authority_mode, :text, null: false
      add :proposal_revision, :bigint, null: false
      add :approval_proposal_revision, :bigint, null: false
      add :actor_role_version, :bigint, null: false
      add :target_revision, :bigint, null: false
      add :access_method_revision, :bigint, null: false
      add :provider_revision, :bigint, null: false
      add :capability, :text, null: false
      add :operation, :text, null: false
      add :selectors, :map, null: false
      add :parameters, :map, null: false
      add :idempotency_key, :text, null: false
      add :authorization_digest, :text, null: false
      add :policy_context, :map, null: false
      add :accepted_at, :utc_datetime_usec, null: false
      add :dispatch_started_at, :utc_datetime_usec
      add :outcome_category, :text
      add :reference, :text
      add :result_details, :map, null: false, default: %{}
      add :completed_at, :utc_datetime_usec
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "operations_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:operations, [:idempotency_key],
             name: "operations_unique_idempotency_index"
           )

    alter table(:operations) do
      add :resolution_run_id,
          references(:resolution_runs,
            column: :id,
            name: "operations_resolution_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :proposal_id,
          references(:proposals,
            column: :id,
            name: "operations_proposal_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:operations, [:proposal_id], name: "operations_unique_proposal_index")

    alter table(:operations) do
      add :approval_id,
          references(:approvals,
            column: :id,
            name: "operations_approval_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :actor_id,
          references(:users,
            column: :id,
            name: "operations_actor_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :target_id,
          references(:targets,
            column: :id,
            name: "operations_target_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :access_method_id,
          references(:access_methods,
            column: :id,
            name: "operations_access_method_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :provider_id,
          references(:providers,
            column: :id,
            name: "operations_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:operations, [:case_id])

    create index(:operations, [:resolution_run_id])

    create index(:operations, [:target_id])
  end

  def down do
    drop_if_exists index(:operations, [:target_id])

    drop_if_exists index(:operations, [:resolution_run_id])

    drop_if_exists index(:operations, [:case_id])

    drop constraint(:operations, "operations_provider_id_fkey")

    drop constraint(:operations, "operations_access_method_id_fkey")

    drop constraint(:operations, "operations_target_id_fkey")

    drop constraint(:operations, "operations_actor_id_fkey")

    drop constraint(:operations, "operations_approval_id_fkey")

    drop constraint(:operations, "operations_proposal_id_fkey")

    drop constraint(:operations, "operations_resolution_run_id_fkey")

    drop constraint(:operations, "operations_case_id_fkey")

    alter table(:operations) do
      remove :provider_id
      remove :access_method_id
      remove :target_id
      remove :actor_id
      remove :approval_id
    end

    drop_if_exists unique_index(:operations, [:proposal_id],
                     name: "operations_unique_proposal_index"
                   )

    alter table(:operations) do
      remove :proposal_id
      remove :resolution_run_id
    end

    drop_if_exists unique_index(:operations, [:idempotency_key],
                     name: "operations_unique_idempotency_index"
                   )

    drop table(:operations)
  end
end
