defmodule Opsonde.Repo.Migrations.AiUsageRoles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ai_usage_role_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :priority, :bigint, null: false, default: 100
      add :enabled, :boolean, null: false, default: true
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :provider_id,
          references(:providers,
            column: :id,
            name: "ai_usage_role_assignments_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:ai_usage_role_assignments, [:provider_id, :role],
             name: "ai_usage_role_assignments_unique_provider_role_index"
           )
  end

  def down do
    drop constraint(:ai_usage_role_assignments, "ai_usage_role_assignments_provider_id_fkey")

    drop_if_exists unique_index(:ai_usage_role_assignments, [:provider_id, :role],
                     name: "ai_usage_role_assignments_unique_provider_role_index"
                   )

    drop table(:ai_usage_role_assignments)
  end
end
