defmodule Opsonde.Repo.Migrations.ProposalMaterialization do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:proposals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false
      add :authority_mode, :text, null: false
      add :case_generation, :bigint, null: false
      add :target_revision, :bigint, null: false
      add :access_method_revision, :bigint, null: false
      add :provider_revision, :bigint, null: false
      add :capability, :text, null: false
      add :operation, :text, null: false
      add :selectors, :map, null: false
      add :parameters, :map, null: false
      add :reason, :text, null: false
      add :evidence_ids, {:array, :uuid}, null: false
      add :expected_result, :map, null: false
      add :verification_intent, :map, null: false
      add :verification_tool, :map, null: false
      add :resolver_identity, :map, null: false
      add :reserved_operation_id, :uuid, null: false
      add :operation_idempotency_key, :text, null: false
      add :preflight_status, :text, null: false
      add :preflight_context, :map, null: false
      add :preflight_reason, :text
      add :proposal_digest, :text, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "proposals_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:proposals, [:reserved_operation_id],
             name: "proposals_unique_reserved_operation_index"
           )

    alter table(:proposals) do
      add :resolution_run_id,
          references(:resolution_runs,
            column: :id,
            name: "proposals_resolution_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :source_turn_id,
          references(:turns,
            column: :id,
            name: "proposals_source_turn_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:proposals, [:source_turn_id], name: "proposals_unique_source_turn_index")

    alter table(:proposals) do
      add :proposed_for_id,
          references(:users,
            column: :id,
            name: "proposals_proposed_for_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :target_id,
          references(:targets,
            column: :id,
            name: "proposals_target_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :access_method_id,
          references(:access_methods,
            column: :id,
            name: "proposals_access_method_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :provider_id,
          references(:providers,
            column: :id,
            name: "proposals_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:proposals, [:case_id])

    create index(:proposals, [:resolution_run_id])

    create index(:proposals, [:target_id])

    create index(:proposals, [:proposed_for_id])
  end

  def down do
    drop_if_exists index(:proposals, [:proposed_for_id])

    drop_if_exists index(:proposals, [:target_id])

    drop_if_exists index(:proposals, [:resolution_run_id])

    drop_if_exists index(:proposals, [:case_id])

    drop constraint(:proposals, "proposals_provider_id_fkey")

    drop constraint(:proposals, "proposals_access_method_id_fkey")

    drop constraint(:proposals, "proposals_target_id_fkey")

    drop constraint(:proposals, "proposals_proposed_for_id_fkey")

    drop constraint(:proposals, "proposals_source_turn_id_fkey")

    drop constraint(:proposals, "proposals_resolution_run_id_fkey")

    drop constraint(:proposals, "proposals_case_id_fkey")

    alter table(:proposals) do
      remove :provider_id
      remove :access_method_id
      remove :target_id
      remove :proposed_for_id
    end

    drop_if_exists unique_index(:proposals, [:source_turn_id],
                     name: "proposals_unique_source_turn_index"
                   )

    alter table(:proposals) do
      remove :source_turn_id
      remove :resolution_run_id
    end

    drop_if_exists unique_index(:proposals, [:reserved_operation_id],
                     name: "proposals_unique_reserved_operation_index"
                   )

    drop table(:proposals)
  end
end
