defmodule Opsonde.Repo.Migrations.AuditSchedules do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:audit_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :schedule_revision, :bigint, null: false
      add :target_key, :text, null: false
      add :target_revision, :bigint
      add :case_revision, :bigint
      add :scheduled_for, :utc_datetime_usec, null: false
      add :status, :text, null: false
      add :reason, :text
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :audit_schedule_id, :uuid, null: false
    end

    create unique_index(:audit_runs, [:audit_schedule_id, :scheduled_for, :target_key],
             name: "audit_runs_unique_occurrence_target_index"
           )

    alter table(:audit_runs) do
      add :target_id,
          references(:targets,
            column: :id,
            name: "audit_runs_target_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :case_id,
          references(:cases,
            column: :id,
            name: "audit_runs_case_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:audit_runs, [:audit_schedule_id])

    create index(:audit_runs, [:target_id])

    create index(:audit_runs, [:case_id])

    create index(:audit_runs, [:status])

    create table(:audit_schedules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:audit_runs) do
      modify :audit_schedule_id,
             references(:audit_schedules,
               column: :id,
               name: "audit_runs_audit_schedule_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create constraint(:audit_runs, :audit_runs_target_pair,
             check: """
               (target_id IS NULL AND target_revision IS NULL) OR (target_id IS NOT NULL AND target_revision IS NOT NULL)
             """
           )

    create constraint(:audit_runs, :audit_runs_case_pair,
             check: """
               (case_id IS NULL AND case_revision IS NULL) OR (case_id IS NOT NULL AND case_revision IS NOT NULL)
             """
           )

    alter table(:audit_schedules) do
      add :name, :text, null: false
      add :objective, :text, null: false
      add :timezone, :text, null: false
      add :cron_expression, :text, null: false
      add :report_language, :text, null: false
      add :target_ids, {:array, :uuid}, null: false, default: []
      add :active, :boolean, null: false, default: true
      add :next_run_at, :utc_datetime_usec, null: false
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :management_boundary_id,
          references(:management_boundaries,
            column: :id,
            name: "audit_schedules_management_boundary_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:audit_schedules, [:name], name: "audit_schedules_unique_name_index")

    create constraint(:audit_schedules, :audit_schedules_one_scope,
             check: """
               (cardinality(target_ids) > 0 AND management_boundary_id IS NULL) OR (cardinality(target_ids) = 0 AND management_boundary_id IS NOT NULL)
             """
           )

    create index(:audit_schedules, [:management_boundary_id])

    create index(:audit_schedules, [:active, :next_run_at])
  end

  def down do
    drop_if_exists index(:audit_schedules, [:active, :next_run_at])

    drop_if_exists index(:audit_schedules, [:management_boundary_id])

    drop_if_exists constraint(:audit_schedules, :audit_schedules_one_scope)

    drop constraint(:audit_schedules, "audit_schedules_management_boundary_id_fkey")

    drop_if_exists unique_index(:audit_schedules, [:name],
                     name: "audit_schedules_unique_name_index"
                   )

    alter table(:audit_schedules) do
      remove :management_boundary_id
      remove :updated_at
      remove :inserted_at
      remove :revision
      remove :next_run_at
      remove :active
      remove :target_ids
      remove :report_language
      remove :cron_expression
      remove :timezone
      remove :objective
      remove :name
    end

    drop_if_exists constraint(:audit_runs, :audit_runs_case_pair)

    drop_if_exists constraint(:audit_runs, :audit_runs_target_pair)

    drop constraint(:audit_runs, "audit_runs_case_id_fkey")

    drop constraint(:audit_runs, "audit_runs_target_id_fkey")

    drop constraint(:audit_runs, "audit_runs_audit_schedule_id_fkey")

    alter table(:audit_runs) do
      modify :audit_schedule_id, :uuid
    end

    drop table(:audit_schedules)

    drop_if_exists index(:audit_runs, [:status])

    drop_if_exists index(:audit_runs, [:case_id])

    drop_if_exists index(:audit_runs, [:target_id])

    drop_if_exists index(:audit_runs, [:audit_schedule_id])

    alter table(:audit_runs) do
      remove :case_id
      remove :target_id
    end

    drop_if_exists unique_index(:audit_runs, [:audit_schedule_id, :scheduled_for, :target_key],
                     name: "audit_runs_unique_occurrence_target_index"
                   )

    drop table(:audit_runs)
  end
end
