defmodule Opsonde.Repo.Migrations.Providers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:providers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :role, :text, null: false
      add :adapter_type, :text, null: false
      add :configuration, :map, null: false, default: %{}
      add :revision, :bigint, null: false, default: 1
      add :enabled, :boolean, null: false, default: false
      add :checked_revision, :bigint
      add :check_status, :text
      add :check_category, :text
      add :check_message, :text
      add :checked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :encrypted_credentials, :binary, null: false
    end

    create unique_index(:providers, [:name], name: "providers_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:providers, [:name], name: "providers_unique_name_index")

    drop table(:providers)
  end
end
