defmodule Opsonde.Repo.Migrations.ConditionSubjectLookupIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:conditions, [:subject_key, :predicate])
  end

  def down do
    drop_if_exists index(:conditions, [:subject_key, :predicate])
  end
end
