defmodule Opsonde.Repo.Migrations.SplitCaseConditions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cases) do
      add :split_parent_id,
          references(:cases,
            column: :id,
            name: "cases_split_parent_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:cases, [:split_parent_id])
  end

  def down do
    drop_if_exists index(:cases, [:split_parent_id])

    drop constraint(:cases, "cases_split_parent_id_fkey")

    alter table(:cases) do
      remove :split_parent_id
    end
  end
end
