defmodule Opsonde.Repo.Migrations.ClassifyBmcParameters do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bmc_operations) do
      add :parameter_classes, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:bmc_operations) do
      remove :parameter_classes
    end
  end
end
