defmodule Opsonde.Repo.Migrations.Baseline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:relationships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :facts, :map, null: false, default: %{}
      add :search_text, :text, null: false
      add :active, :boolean, null: false, default: true
      add :valid_until, :utc_datetime_usec
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_target_id, :uuid, null: false
      add :destination_target_id, :uuid, null: false
    end

    create unique_index(:relationships, [:source_target_id, :destination_target_id, :kind],
             name: "relationships_unique_typed_edge_index"
           )

    create index(:relationships, [:source_target_id])

    create index(:relationships, [:destination_target_id])

    create table(:turns, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ordinal, :bigint, null: false
      add :idempotency_key, :text, null: false
      add :status, :text, null: false
      add :intent, :map, null: false
      add :result, :map, null: false, default: %{}
      add :result_digest, :text
      add :progress_kind, :text
      add :started_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid, null: false
      add :resolution_run_id, :uuid, null: false
    end

    create unique_index(:turns, [:resolution_run_id, :idempotency_key],
             name: "turns_unique_idempotency_index"
           )

    create unique_index(:turns, [:resolution_run_id, :ordinal],
             name: "turns_unique_ordinal_index"
           )

    create index(:turns, [:case_id])

    create index(:turns, [:resolution_run_id])

    create table(:signal_correlations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source, :text, null: false
      add :event_key, :text, null: false
      add :current_state, :text, null: false, default: "pending"
      add :current_occurred_at, :utc_datetime_usec
      add :current_source_sequence, :text
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :provider_id, :uuid, null: false
    end

    create unique_index(:signal_correlations, [:provider_id, :source, :event_key],
             name: "signal_correlations_unique_source_event_index"
           )

    alter table(:signal_correlations) do
      add :latest_signal_event_id, :uuid
    end

    create index(:signal_correlations, [:provider_id])

    create index(:signal_correlations, [:latest_signal_event_id])

    create table(:targets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:relationships) do
      modify :source_target_id,
             references(:targets,
               column: :id,
               name: "relationships_source_target_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :destination_target_id,
             references(:targets,
               column: :id,
               name: "relationships_destination_target_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:targets) do
      add :name, :text, null: false
      add :kind, :text, null: false
      add :type_id, :text, null: false
      add :facts, :map, null: false, default: %{}
      add :operating_instructions, :text, null: false, default: ""
      add :search_text, :text, null: false
      add :active, :boolean, null: false, default: true
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :management_boundary_id, :uuid
    end

    create index(:targets, [:management_boundary_id])

    create table(:resolution_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:turns) do
      modify :resolution_run_id,
             references(:resolution_runs,
               column: :id,
               name: "turns_resolution_run_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:resolution_runs) do
      add :generation, :bigint, null: false
      add :active, :boolean, null: false
      add :status, :text, null: false
      add :authority_mode, :text, null: false
      add :max_elapsed_seconds, :bigint, null: false
      add :max_resolver_turns, :bigint, null: false
      add :max_target_requests, :bigint, null: false
      add :max_effects, :bigint, null: false
      add :max_related_targets, :bigint, null: false
      add :max_ai_usage_units, :bigint, null: false
      add :max_no_progress_turns, :bigint, null: false
      add :turn_count, :bigint, null: false, default: 0
      add :target_request_count, :bigint, null: false, default: 0
      add :effect_count, :bigint, null: false, default: 0
      add :related_target_count, :bigint, null: false, default: 0
      add :ai_usage_units, :bigint, null: false, default: 0
      add :no_progress_turns, :bigint, null: false, default: 0
      add :started_at, :utc_datetime_usec, null: false
      add :deadline_at, :utc_datetime_usec, null: false
      add :ended_at, :utc_datetime_usec
      add :resume_reason, :text
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid, null: false
    end

    create unique_index(:resolution_runs, [:case_id, :generation],
             name: "resolution_runs_unique_generation_index"
           )

    alter table(:resolution_runs) do
      add :resumed_by_id, :uuid
    end

    create index(:resolution_runs, [:resumed_by_id])

    create table(:management_boundaries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:targets) do
      modify :management_boundary_id,
             references(:management_boundaries,
               column: :id,
               name: "targets_management_boundary_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:management_boundaries) do
      add :name, :text, null: false
      add :kind, :text, null: false
      add :facts, :map, null: false, default: %{}
      add :active, :boolean, null: false, default: true
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:management_boundaries, [:name],
             name: "management_boundaries_unique_name_index"
           )

    create table(:inventory_import_rows, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false
      add :disposition, :text, null: false
      add :identity_source, :text, null: false
      add :identity_kind, :text, null: false
      add :identity_value, :text, null: false
      add :candidate, :map, null: false, default: %{}
      add :provenance, :map, null: false, default: %{}
      add :errors, {:array, :text}, null: false, default: []
      add :target_revision, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inventory_import_id, :uuid, null: false
    end

    create unique_index(:inventory_import_rows, [:inventory_import_id, :position],
             name: "inventory_import_rows_unique_import_position_index"
           )

    alter table(:inventory_import_rows) do
      add :target_id,
          references(:targets,
            column: :id,
            name: "inventory_import_rows_target_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:inventory_import_rows, [:inventory_import_id])

    create index(:inventory_import_rows, [:target_id])

    create table(:report_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :scope, :text, null: false, default: "global"
      add :automatic_case_reports_enabled, :boolean, null: false, default: true
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :changed_by_id, :uuid
    end

    create unique_index(:report_settings, [:scope], name: "report_settings_unique_scope_index")

    create table(:case_dispatches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :state, :text, null: false
      add :first_received_at, :utc_datetime_usec, null: false
      add :due_at, :utc_datetime_usec, null: false
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid, null: false
    end

    create unique_index(:case_dispatches, [:case_id],
             name: "case_dispatches_one_dispatch_per_case_index"
           )

    alter table(:case_dispatches) do
      add :anchor_target_id,
          references(:targets,
            column: :id,
            name: "case_dispatches_anchor_target_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:approvals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :decision, :text, null: false
      add :source, :text, null: false
      add :proposal_digest, :text, null: false
      add :proposal_revision, :bigint, null: false
      add :case_generation, :bigint, null: false
      add :actor_role_version, :bigint, null: false
      add :clearance_digest, :text
      add :reason, :text, null: false
      add :decided_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :proposal_id, :uuid, null: false
    end

    create unique_index(:approvals, [:proposal_id], name: "approvals_unique_proposal_index")

    alter table(:approvals) do
      add :case_id, :uuid, null: false

      add :resolution_run_id,
          references(:resolution_runs,
            column: :id,
            name: "approvals_resolution_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :actor_id, :uuid, null: false
    end

    create index(:approvals, [:case_id])

    create index(:approvals, [:resolution_run_id])

    create index(:approvals, [:actor_id])

    create table(:case_condition_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :attached_at, :utc_datetime_usec, null: false
      add :detached_at, :utc_datetime_usec
      add :reason, :text, null: false
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid, null: false
      add :condition_id, :uuid, null: false
    end

    create table(:audit_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :schedule_revision, :bigint, null: false
      add :target_key, :text, null: false
      add :target_revision, :bigint
      add :case_revision, :bigint
      add :scheduled_for, :utc_datetime_usec, null: false
      add :status, :text, null: false
      add :reason, :text
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :audit_schedule_id, :uuid, null: false
    end

    create unique_index(:audit_runs, [:audit_schedule_id, :scheduled_for, :target_key],
             name: "audit_runs_unique_occurrence_target_index"
           )

    alter table(:audit_runs) do
      add :target_id,
          references(:targets,
            column: :id,
            name: "audit_runs_target_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :case_id, :uuid
    end

    create index(:audit_runs, [:audit_schedule_id])

    create index(:audit_runs, [:target_id])

    create index(:audit_runs, [:case_id])

    create index(:audit_runs, [:status])

    create table(:proposals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:approvals) do
      modify :proposal_id,
             references(:proposals,
               column: :id,
               name: "approvals_proposal_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:proposals) do
      add :status, :text, null: false
      add :authority_mode, :text, null: false
      add :case_generation, :bigint, null: false
      add :target_revision, :bigint, null: false
      add :access_method_revision, :bigint, null: false
      add :provider_revision, :bigint, null: false
      add :request_kind, :text, null: false
      add :tool_id, :text, null: false
      add :capability, :text, null: false
      add :operation, :text, null: false
      add :selectors, :map, null: false
      add :parameters, :map, null: false
      add :reason, :text, null: false
      add :evidence_ids, {:array, :uuid}, null: false
      add :affected_conditions, {:array, :map}, null: false, default: []
      add :expected_result, :map, null: false
      add :verification_intent, :map, null: false
      add :verification_tool, :map, null: false
      add :resolver_identity, :map, null: false
      add :reserved_operation_id, :uuid, null: false
      add :operation_idempotency_key, :text, null: false
      add :preflight_status, :text, null: false
      add :preflight_context, :map, null: false
      add :preflight_reason, :text
      add :proposal_digest, :text, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid, null: false
    end

    create unique_index(:proposals, [:reserved_operation_id],
             name: "proposals_unique_reserved_operation_index"
           )

    alter table(:proposals) do
      add :resolution_run_id,
          references(:resolution_runs,
            column: :id,
            name: "proposals_resolution_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :source_turn_id,
          references(:turns,
            column: :id,
            name: "proposals_source_turn_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:proposals, [:source_turn_id], name: "proposals_unique_source_turn_index")

    alter table(:proposals) do
      add :proposed_for_id, :uuid, null: false

      add :target_id,
          references(:targets,
            column: :id,
            name: "proposals_target_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :access_method_id, :uuid, null: false
      add :provider_id, :uuid, null: false
    end

    create index(:proposals, [:case_id])

    create index(:proposals, [:resolution_run_id])

    create index(:proposals, [:target_id])

    create index(:proposals, [:proposed_for_id])

    create table(:oidc_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :purpose, :text, null: false
      add :start_token_digest, :binary, null: false
      add :browser_binding_digest, :binary
      add :verifier_digest, :binary
      add :code_digest, :binary
      add :redirect_uri, :text
      add :expires_at, :utc_datetime_usec, null: false
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :consumed_at, :utc_datetime_usec
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
    end

    create table(:audit_schedules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:audit_runs) do
      modify :audit_schedule_id,
             references(:audit_schedules,
               column: :id,
               name: "audit_runs_audit_schedule_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:audit_schedules) do
      add :name, :text, null: false
      add :objective, :text, null: false
      add :timezone, :text, null: false
      add :cron_expression, :text, null: false
      add :report_language, :text, null: false
      add :target_ids, {:array, :uuid}, null: false, default: []
      add :active, :boolean, null: false, default: true
      add :next_run_at, :utc_datetime_usec, null: false
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :management_boundary_id,
          references(:management_boundaries,
            column: :id,
            name: "audit_schedules_management_boundary_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:audit_schedules, [:name], name: "audit_schedules_unique_name_index")

    create constraint(:audit_schedules, :audit_schedules_one_scope,
             check: """
               (cardinality(target_ids) > 0 AND management_boundary_id IS NULL) OR (cardinality(target_ids) = 0 AND management_boundary_id IS NOT NULL)
             """
           )

    create index(:audit_schedules, [:management_boundary_id])

    create index(:audit_schedules, [:active, :next_run_at])

    create table(:conditions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:case_condition_memberships) do
      modify :condition_id,
             references(:conditions,
               column: :id,
               name: "case_condition_memberships_condition_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:conditions) do
      add :occurrence, :bigint, null: false
      add :predicate, :text, null: false
      add :subject_key, :text, null: false
      add :subject_ref, :map, null: false, default: %{}
      add :state, :text, null: false
      add :first_fired_at, :utc_datetime_usec, null: false
      add :current_occurred_at, :utc_datetime_usec, null: false
      add :current_source_sequence, :text
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :signal_correlation_id,
          references(:signal_correlations,
            column: :id,
            name: "conditions_signal_correlation_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:conditions, [:signal_correlation_id, :occurrence],
             name: "conditions_unique_occurrence_index"
           )

    alter table(:conditions) do
      add :target_id,
          references(:targets,
            column: :id,
            name: "conditions_target_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:conditions, [:signal_correlation_id, :subject_key, :predicate],
             name: "conditions_one_firing_subject",
             unique: true,
             where: "state = 'firing'"
           )

    create index(:conditions, [:target_id])

    create index(:conditions, [:subject_key, :predicate])

    create table(:external_identities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source, :text, null: false
      add :kind, :text, null: false
      add :value, :text, null: false
      add :search_text, :text, null: false
      add :active, :boolean, null: false, default: true
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :target_id,
          references(:targets,
            column: :id,
            name: "external_identities_target_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:external_identities, [:source, :kind, :value],
             name: "external_identities_unique_source_identity_index"
           )

    create index(:external_identities, [:target_id])

    create table(:signal_receipts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider_revision, :bigint, null: false
      add :receipt_id, :text, null: false
      add :source, :text, null: false
      add :received_at, :utc_datetime_usec, null: false
      add :metadata, :map, null: false, default: %{}
      add :normalized_digest, :text, null: false
      add :event_count, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :provider_id, :uuid, null: false
    end

    create unique_index(:signal_receipts, [:provider_id, :receipt_id],
             name: "signal_receipts_unique_source_receipt_index"
           )

    create index(:signal_receipts, [:provider_id])

    create index(:signal_receipts, [:source])

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:resolution_runs) do
      modify :resumed_by_id,
             references(:users,
               column: :id,
               name: "resolution_runs_resumed_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:report_settings) do
      modify :changed_by_id,
             references(:users,
               column: :id,
               name: "report_settings_changed_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:approvals) do
      modify :actor_id,
             references(:users,
               column: :id,
               name: "approvals_actor_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:proposals) do
      modify :proposed_for_id,
             references(:users,
               column: :id,
               name: "proposals_proposed_for_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:oidc_requests) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "oidc_requests_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:users) do
      add :email, :citext, null: false
      add :hashed_password, :text, null: false
      add :role, :text, null: false, default: "viewer"
      add :role_version, :bigint, null: false, default: 1
      add :preferred_language, :text, null: false, default: "en"
      add :bootstrap_marker, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:bootstrap_marker], name: "users_single_bootstrap_admin_index")

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:review_decisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :outcome, :text, null: false
      add :verdict, :text, null: false
      add :category, :text
      add :reason, :text, null: false
      add :selection_source, :text
      add :provider_revision, :bigint
      add :assignment_revision, :bigint
      add :session_id, :text, null: false
      add :resolver_session_id, :text, null: false
      add :proposal_digest, :text, null: false
      add :input_tokens, :bigint, null: false
      add :output_tokens, :bigint, null: false
      add :result_digest, :text, null: false
      add :decided_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :proposal_id,
          references(:proposals,
            column: :id,
            name: "review_decisions_proposal_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:review_decisions, [:proposal_id],
             name: "review_decisions_unique_proposal_index"
           )

    alter table(:review_decisions) do
      add :case_id, :uuid, null: false

      add :resolution_run_id,
          references(:resolution_runs,
            column: :id,
            name: "review_decisions_resolution_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :provider_id, :uuid
      add :assignment_id, :uuid
    end

    create index(:review_decisions, [:case_id])

    create index(:review_decisions, [:resolution_run_id])

    create index(:review_decisions, [:provider_id])

    create index(:review_decisions, [:assignment_id])

    create table(:authority_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :scope, :text, null: false, default: "global"
      add :authority_mode, :text, null: false
      add :signal_automation_enabled, :boolean, null: false
      add :max_elapsed_seconds, :bigint, null: false
      add :max_resolver_turns, :bigint, null: false
      add :max_target_requests, :bigint, null: false
      add :max_effects, :bigint, null: false
      add :max_related_targets, :bigint, null: false
      add :max_ai_usage_units, :bigint, null: false
      add :max_no_progress_turns, :bigint, null: false
      add :setting_revision, :bigint, null: false
      add :active, :boolean, null: false
      add :reason, :text, null: false
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :changed_by_id,
          references(:users,
            column: :id,
            name: "authority_settings_changed_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:authority_settings, [:scope, :setting_revision],
             name: "authority_settings_unique_setting_revision_index"
           )

    create unique_index(:authority_settings, [:scope],
             name: "authority_settings_one_current_index",
             where: "(active = TRUE)"
           )

    create index(:authority_settings, [:changed_by_id])

    create table(:verification_attempts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false
      add :case_generation, :bigint, null: false
      add :authority_mode, :text, null: false
      add :actor_role_version, :bigint, null: false
      add :target_revision, :bigint, null: false
      add :access_method_revision, :bigint, null: false
      add :provider_revision, :bigint, null: false
      add :tool_id, :text, null: false
      add :capability, :text, null: false
      add :operation, :text, null: false
      add :selectors, :map, null: false
      add :parameters, :map, null: false
      add :expected, :map, null: false
      add :operation_reference, :text
      add :authorization_digest, :text, null: false
      add :accepted_at, :utc_datetime_usec, null: false
      add :dispatch_started_at, :utc_datetime_usec
      add :outcome_category, :text
      add :facts, :map, null: false, default: %{}
      add :provider_evidence, :map, null: false, default: %{}
      add :observed_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid, null: false

      add :resolution_run_id,
          references(:resolution_runs,
            column: :id,
            name: "verification_attempts_resolution_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :operation_id, :uuid, null: false
    end

    create unique_index(:verification_attempts, [:operation_id],
             name: "verification_attempts_unique_operation_index"
           )

    alter table(:verification_attempts) do
      add :proposal_id,
          references(:proposals,
            column: :id,
            name: "verification_attempts_proposal_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :actor_id,
          references(:users,
            column: :id,
            name: "verification_attempts_actor_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :target_id,
          references(:targets,
            column: :id,
            name: "verification_attempts_target_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :access_method_id, :uuid, null: false
      add :provider_id, :uuid, null: false
    end

    create index(:verification_attempts, [:case_id])

    create index(:verification_attempts, [:resolution_run_id])

    create index(:verification_attempts, [:target_id])

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:signal_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:signal_correlations) do
      modify :latest_signal_event_id,
             references(:signal_events,
               column: :id,
               name: "signal_correlations_latest_signal_event_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:signal_events) do
      add :event_key, :text, null: false
      add :state, :text, null: false
      add :source_sequence, :text
      add :occurred_at, :utc_datetime_usec, null: false
      add :target_ref, :map
      add :attributes, :map, null: false, default: %{}
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :signal_receipt_id,
          references(:signal_receipts,
            column: :id,
            name: "signal_events_signal_receipt_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :signal_correlation_id,
          references(:signal_correlations,
            column: :id,
            name: "signal_events_signal_correlation_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:signal_events, [:signal_receipt_id, :signal_correlation_id],
             name: "signal_events_unique_receipt_event_index"
           )

    alter table(:signal_events) do
      add :condition_id,
          references(:conditions,
            column: :id,
            name: "signal_events_condition_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :case_id, :uuid

      add :target_id,
          references(:targets,
            column: :id,
            name: "signal_events_target_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:signal_events, [:signal_receipt_id])

    create index(:signal_events, [:signal_correlation_id])

    create index(:signal_events, [:condition_id])

    create index(:signal_events, [:case_id])

    create index(:signal_events, [:target_id])

    create table(:oidc_providers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :issuer, :text, null: false
      add :client_id, :text, null: false
      add :id_token_alg, :text, null: false, default: "RS256"
      add :enabled, :boolean, null: false, default: true
      add :revision, :bigint, null: false, default: 1
      add :singleton, :text, null: false, default: "oidc"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :encrypted_client_secret, :binary, null: false
    end

    create unique_index(:oidc_providers, [:singleton],
             name: "oidc_providers_one_oidc_provider_index"
           )

    create table(:cases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:turns) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "turns_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:turns, [:resolution_run_id],
             name: "turns_one_started_turn_index",
             where: "(status = 'started')"
           )

    alter table(:resolution_runs) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "resolution_runs_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:resolution_runs, [:case_id],
             name: "resolution_runs_one_active_run_index",
             where: "(active = TRUE)"
           )

    alter table(:case_dispatches) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "case_dispatches_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:approvals) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "approvals_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:case_condition_memberships) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "case_condition_memberships_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:case_condition_memberships, [:condition_id],
             name: "case_condition_one_active_owner",
             unique: true,
             where: "detached_at IS NULL"
           )

    create index(:case_condition_memberships, [:case_id], where: "detached_at IS NULL")

    alter table(:audit_runs) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "audit_runs_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create constraint(:audit_runs, :audit_runs_target_pair,
             check: """
               (target_id IS NULL AND target_revision IS NULL) OR (target_id IS NOT NULL AND target_revision IS NOT NULL)
             """
           )

    create constraint(:audit_runs, :audit_runs_case_pair,
             check: """
               (case_id IS NULL AND case_revision IS NULL) OR (case_id IS NOT NULL AND case_revision IS NOT NULL)
             """
           )

    alter table(:proposals) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "proposals_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:review_decisions) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "review_decisions_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:verification_attempts) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "verification_attempts_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:signal_events) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "signal_events_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:cases) do
      add :trigger_kind, :text, null: false
      add :source, :text, null: false
      add :source_ref, :text, null: false
      add :title, :text, null: false
      add :severity, :text, null: false
      add :report_language, :text, null: false, default: "en"
      add :status, :text, null: false
      add :initial_context, :map, null: false, default: %{}
      add :authority_setting_revision, :bigint, null: false
      add :authority_mode, :text, null: false
      add :max_elapsed_seconds, :bigint, null: false
      add :max_resolver_turns, :bigint, null: false
      add :max_target_requests, :bigint, null: false
      add :max_effects, :bigint, null: false
      add :max_related_targets, :bigint, null: false
      add :max_ai_usage_units, :bigint, null: false
      add :max_no_progress_turns, :bigint, null: false
      add :cancel_requested, :boolean, null: false, default: false
      add :stop_reason, :text
      add :pending_intent, :map, null: false, default: %{}
      add :required_human_input, :text
      add :resolved_at, :utc_datetime_usec
      add :recovery_baseline_at, :utc_datetime_usec
      add :revision, :bigint, null: false, default: 1
      add :selected_target_revision, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :split_parent_id,
          references(:cases,
            column: :id,
            name: "cases_split_parent_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :authority_setting_id,
          references(:authority_settings,
            column: :id,
            name: "cases_authority_setting_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :initial_target_id,
          references(:targets,
            column: :id,
            name: "cases_initial_target_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :selected_target_id,
          references(:targets,
            column: :id,
            name: "cases_selected_target_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :current_owner_id,
          references(:users,
            column: :id,
            name: "cases_current_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:cases, [:trigger_kind, :source, :source_ref],
             name: "cases_one_active_signal_trigger_index",
             where: "(trigger_kind = 'signal' AND status IN ('running', 'needs_attention'))"
           )

    create unique_index(:cases, [:trigger_kind, :source, :source_ref],
             name: "cases_unique_trigger_index",
             where: "(trigger_kind <> 'signal')"
           )

    create constraint(:cases, :cases_selected_target_pair,
             check: """
               (selected_target_id IS NULL AND selected_target_revision IS NULL) OR (selected_target_id IS NOT NULL AND selected_target_revision IS NOT NULL)
             """
           )

    create index(:cases, [:authority_setting_id])

    create index(:cases, [:split_parent_id])

    create index(:cases, [:initial_target_id])

    create index(:cases, [:selected_target_id])

    create index(:cases, [:current_owner_id])

    create table(:case_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_type, :text, null: false
      add :idempotency_key, :text
      add :data, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "case_events_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:case_events, [:case_id, :idempotency_key],
             name: "case_events_unique_idempotency_index"
           )

    alter table(:case_events) do
      add :resolution_run_id,
          references(:resolution_runs,
            column: :id,
            name: "case_events_resolution_run_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :actor_id,
          references(:users,
            column: :id,
            name: "case_events_actor_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:case_events, [:case_id])

    create index(:case_events, [:resolution_run_id])

    create index(:case_events, [:actor_id])

    create table(:deliveries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :report_revision, :bigint, null: false
      add :provider_revision, :bigint, null: false
      add :destination_id, :uuid, null: false
      add :destination_revision, :bigint, null: false
      add :idempotency_key, :text, null: false
      add :status, :text, null: false
      add :reference, :text
      add :details, :map, null: false, default: %{}
      add :enqueued_at, :utc_datetime_usec, null: false
      add :dispatch_started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :revision, :bigint, null: false, default: 1
      add :report_id, :uuid, null: false
    end

    create unique_index(:deliveries, [:idempotency_key],
             name: "deliveries_unique_idempotency_index"
           )

    alter table(:deliveries) do
      add :provider_id, :uuid, null: false
    end

    create index(:deliveries, [:report_id])

    create index(:deliveries, [:provider_id])

    create index(:deliveries, [:status])

    create table(:reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:deliveries) do
      modify :report_id,
             references(:reports,
               column: :id,
               name: "deliveries_report_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:reports) do
      add :case_revision, :bigint, null: false
      add :language, :text, null: false
      add :outcome, :text, null: false
      add :content, :map, null: false
      add :content_digest, :text, null: false
      add :generated_at, :utc_datetime_usec, null: false
      add :revision, :bigint, null: false, default: 1

      add :case_id,
          references(:cases,
            column: :id,
            name: "reports_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:reports, [:case_id, :case_revision],
             name: "reports_unique_case_revision_index"
           )

    create index(:reports, [:case_id])

    create table(:user_identities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :strategy, :text, null: false
      add :uid, :text, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "user_identities_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:user_identities, [:strategy, :user_id],
             name: "user_identities_one_identity_per_strategy_and_user_index"
           )

    create unique_index(:user_identities, [:strategy, :uid],
             name: "user_identities_unique_on_strategy_and_uid_index"
           )

    create table(:evidences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :idempotency_key, :text, null: false
      add :kind, :text, null: false
      add :source, :text, null: false
      add :source_ref, :text, null: false
      add :content, :map, null: false
      add :observed_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "evidences_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:evidences, [:case_id, :idempotency_key],
             name: "evidences_unique_idempotency_index"
           )

    alter table(:evidences) do
      add :resolution_run_id,
          references(:resolution_runs,
            column: :id,
            name: "evidences_resolution_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :turn_id,
          references(:turns,
            column: :id,
            name: "evidences_turn_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:evidences, [:case_id])

    create index(:evidences, [:resolution_run_id])

    create index(:evidences, [:turn_id])

    create table(:access_methods, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:proposals) do
      modify :access_method_id,
             references(:access_methods,
               column: :id,
               name: "proposals_access_method_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:verification_attempts) do
      modify :access_method_id,
             references(:access_methods,
               column: :id,
               name: "verification_attempts_access_method_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:access_methods) do
      add :connection_revision, :bigint, null: false, default: 1
      add :check_attempt_id, :uuid
      add :check_status, :text
      add :checked_connection_revision, :bigint
      add :checked_target_revision, :bigint
      add :check_message, :text
      add :checked_at, :utc_datetime_usec
      add :observed_capabilities, {:array, :text}, null: false, default: []
      add :operation_catalog, :map
      add :name, :text, null: false
      add :method, :text, null: false
      add :endpoint, :text, null: false
      add :provider_revision, :bigint, null: false
      add :priority, :bigint, null: false, default: 100
      add :capabilities, {:array, :text}, null: false, default: []
      add :active, :boolean, null: false, default: true
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :target_id,
          references(:targets,
            column: :id,
            name: "access_methods_target_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:access_methods, [:target_id, :name],
             name: "access_methods_unique_target_name_index"
           )

    alter table(:access_methods) do
      add :provider_id, :uuid, null: false
    end

    create index(:access_methods, [:target_id])

    create index(:access_methods, [:provider_id])

    create table(:inventory_imports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:inventory_import_rows) do
      modify :inventory_import_id,
             references(:inventory_imports,
               column: :id,
               name: "inventory_import_rows_inventory_import_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_imports) do
      add :source_type, :text, null: false
      add :source, :text, null: false
      add :status, :text, null: false
      add :snapshot_status, :text
      add :source_version, :text
      add :content_digest, :text, null: false
      add :row_count, :bigint, null: false
      add :error_count, :bigint, null: false
      add :revision, :bigint, null: false, default: 1
      add :applied_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :provider_id, :uuid

      add :created_by_id,
          references(:users,
            column: :id,
            name: "inventory_imports_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:inventory_imports, [:provider_id])

    create index(:inventory_imports, [:created_by_id])

    create table(:ai_usage_role_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:review_decisions) do
      modify :assignment_id,
             references(:ai_usage_role_assignments,
               column: :id,
               name: "review_decisions_assignment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:ai_usage_role_assignments) do
      add :role, :text, null: false
      add :priority, :bigint, null: false, default: 100
      add :enabled, :boolean, null: false, default: true
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :provider_id, :uuid, null: false
    end

    create unique_index(:ai_usage_role_assignments, [:provider_id, :role],
             name: "ai_usage_role_assignments_unique_provider_role_index"
           )

    create table(:providers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:signal_correlations) do
      modify :provider_id,
             references(:providers,
               column: :id,
               name: "signal_correlations_provider_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:proposals) do
      modify :provider_id,
             references(:providers,
               column: :id,
               name: "proposals_provider_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:signal_receipts) do
      modify :provider_id,
             references(:providers,
               column: :id,
               name: "signal_receipts_provider_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:review_decisions) do
      modify :provider_id,
             references(:providers,
               column: :id,
               name: "review_decisions_provider_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:verification_attempts) do
      modify :provider_id,
             references(:providers,
               column: :id,
               name: "verification_attempts_provider_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:deliveries) do
      modify :provider_id,
             references(:providers,
               column: :id,
               name: "deliveries_provider_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:access_methods) do
      modify :provider_id,
             references(:providers,
               column: :id,
               name: "access_methods_provider_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inventory_imports) do
      modify :provider_id,
             references(:providers,
               column: :id,
               name: "inventory_imports_provider_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:ai_usage_role_assignments) do
      modify :provider_id,
             references(:providers,
               column: :id,
               name: "ai_usage_role_assignments_provider_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:providers) do
      add :name, :text, null: false
      add :kind, :text, null: false
      add :adapter_type, :text, null: false
      add :configuration, :map, null: false, default: %{}
      add :revision, :bigint, null: false, default: 1
      add :enabled, :boolean, null: false, default: false
      add :checked_revision, :bigint
      add :check_status, :text
      add :check_category, :text
      add :check_message, :text
      add :checked_at, :utc_datetime_usec
      add :retired_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :encrypted_credentials, :binary, null: false
    end

    create unique_index(:providers, [:name],
             name: "providers_unique_name_index",
             where: "(retired_at IS NULL)"
           )

    create table(:ai_invocations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :status, :text, null: false
      add :idempotency_key, :text, null: false
      add :request_digest, :text, null: false
      add :provider_revision, :bigint, null: false
      add :assignment_revision, :bigint, null: false
      add :selection_source, :text, null: false
      add :reserved_units, :bigint, null: false
      add :input_tokens, :bigint, null: false, default: 0
      add :output_tokens, :bigint, null: false, default: 0
      add :cached_tokens, :bigint
      add :reasoning_tokens, :bigint
      add :finish_reason, :text
      add :category, :text
      add :failure_code, :text
      add :rejection_path, :text
      add :result_digest, :text
      add :dispatch_started_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "ai_invocations_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:ai_invocations, [:idempotency_key],
             name: "ai_invocations_unique_idempotency_index"
           )

    alter table(:ai_invocations) do
      add :resolution_run_id,
          references(:resolution_runs,
            column: :id,
            name: "ai_invocations_resolution_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :turn_id,
          references(:turns,
            column: :id,
            name: "ai_invocations_turn_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :proposal_id,
          references(:proposals,
            column: :id,
            name: "ai_invocations_proposal_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :provider_id,
          references(:providers,
            column: :id,
            name: "ai_invocations_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :assignment_id,
          references(:ai_usage_role_assignments,
            column: :id,
            name: "ai_invocations_assignment_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:ai_invocations, [:case_id])

    create index(:ai_invocations, [:resolution_run_id])

    create index(:ai_invocations, [:turn_id])

    create index(:ai_invocations, [:proposal_id])

    create table(:operations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:verification_attempts) do
      modify :operation_id,
             references(:operations,
               column: :id,
               name: "verification_attempts_operation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:operations) do
      add :case_generation, :bigint, null: false
      add :authority_mode, :text, null: false
      add :proposal_revision, :bigint, null: false
      add :approval_proposal_revision, :bigint, null: false
      add :actor_role_version, :bigint, null: false
      add :target_revision, :bigint, null: false
      add :access_method_revision, :bigint, null: false
      add :provider_revision, :bigint, null: false
      add :request_kind, :text, null: false
      add :capability, :text, null: false
      add :operation, :text, null: false
      add :selectors, :map, null: false
      add :resource_scope, :text, null: false
      add :parameters, :map, null: false
      add :idempotency_key, :text, null: false
      add :authorization_digest, :text, null: false
      add :accepted_at, :utc_datetime_usec, null: false
      add :dispatch_started_at, :utc_datetime_usec
      add :outcome_category, :text
      add :reference, :text
      add :result_details, :map, null: false, default: %{}
      add :completed_at, :utc_datetime_usec
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :status, :text, null: false, default: "queued"

      add :case_id,
          references(:cases,
            column: :id,
            name: "operations_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:operations, [:idempotency_key],
             name: "operations_unique_idempotency_index"
           )

    alter table(:operations) do
      add :resolution_run_id,
          references(:resolution_runs,
            column: :id,
            name: "operations_resolution_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :proposal_id,
          references(:proposals,
            column: :id,
            name: "operations_proposal_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create unique_index(:operations, [:proposal_id], name: "operations_unique_proposal_index")

    alter table(:operations) do
      add :approval_id,
          references(:approvals,
            column: :id,
            name: "operations_approval_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :actor_id,
          references(:users,
            column: :id,
            name: "operations_actor_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :target_id,
          references(:targets,
            column: :id,
            name: "operations_target_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :access_method_id,
          references(:access_methods,
            column: :id,
            name: "operations_access_method_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :provider_id,
          references(:providers,
            column: :id,
            name: "operations_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:operations, [:case_id])

    create index(:operations, [:resolution_run_id])

    create index(:operations, [:target_id])

    create index(:operations, [:target_id, :resource_scope])


  end

  def down do
    drop_if_exists index(:operations, [:target_id, :resource_scope])

    drop_if_exists index(:operations, [:target_id])

    drop_if_exists index(:operations, [:resolution_run_id])

    drop_if_exists index(:operations, [:case_id])

    drop constraint(:operations, "operations_provider_id_fkey")

    drop constraint(:operations, "operations_access_method_id_fkey")

    drop constraint(:operations, "operations_target_id_fkey")

    drop constraint(:operations, "operations_actor_id_fkey")

    drop constraint(:operations, "operations_approval_id_fkey")

    drop constraint(:operations, "operations_proposal_id_fkey")

    drop constraint(:operations, "operations_resolution_run_id_fkey")

    drop constraint(:operations, "operations_case_id_fkey")

    alter table(:operations) do
      remove :provider_id
      remove :access_method_id
      remove :target_id
      remove :actor_id
      remove :approval_id
    end

    drop_if_exists unique_index(:operations, [:proposal_id],
                     name: "operations_unique_proposal_index"
                   )

    alter table(:operations) do
      remove :proposal_id
      remove :resolution_run_id
    end

    drop_if_exists unique_index(:operations, [:idempotency_key],
                     name: "operations_unique_idempotency_index"
                   )

    alter table(:operations) do
      remove :case_id
      remove :status
      remove :updated_at
      remove :inserted_at
      remove :revision
      remove :completed_at
      remove :result_details
      remove :reference
      remove :outcome_category
      remove :dispatch_started_at
      remove :accepted_at
      remove :authorization_digest
      remove :idempotency_key
      remove :parameters
      remove :resource_scope
      remove :selectors
      remove :operation
      remove :capability
      remove :request_kind
      remove :provider_revision
      remove :access_method_revision
      remove :target_revision
      remove :actor_role_version
      remove :approval_proposal_revision
      remove :proposal_revision
      remove :authority_mode
      remove :case_generation
    end

    drop constraint(:verification_attempts, "verification_attempts_provider_id_fkey")

    drop constraint(:verification_attempts, "verification_attempts_access_method_id_fkey")

    drop constraint(:verification_attempts, "verification_attempts_target_id_fkey")

    drop constraint(:verification_attempts, "verification_attempts_actor_id_fkey")

    drop constraint(:verification_attempts, "verification_attempts_proposal_id_fkey")

    drop constraint(:verification_attempts, "verification_attempts_operation_id_fkey")

    drop constraint(:verification_attempts, "verification_attempts_resolution_run_id_fkey")

    drop constraint(:verification_attempts, "verification_attempts_case_id_fkey")

    alter table(:verification_attempts) do
      modify :operation_id, :uuid
    end

    drop table(:operations)

    drop_if_exists index(:ai_invocations, [:proposal_id])

    drop_if_exists index(:ai_invocations, [:turn_id])

    drop_if_exists index(:ai_invocations, [:resolution_run_id])

    drop_if_exists index(:ai_invocations, [:case_id])

    drop constraint(:ai_invocations, "ai_invocations_assignment_id_fkey")

    drop constraint(:ai_invocations, "ai_invocations_provider_id_fkey")

    drop constraint(:ai_invocations, "ai_invocations_proposal_id_fkey")

    drop constraint(:ai_invocations, "ai_invocations_turn_id_fkey")

    drop constraint(:ai_invocations, "ai_invocations_resolution_run_id_fkey")

    drop constraint(:ai_invocations, "ai_invocations_case_id_fkey")

    alter table(:ai_invocations) do
      remove :assignment_id
      remove :provider_id
      remove :proposal_id
      remove :turn_id
      remove :resolution_run_id
    end

    drop_if_exists unique_index(:ai_invocations, [:idempotency_key],
                     name: "ai_invocations_unique_idempotency_index"
                   )

    drop table(:ai_invocations)

    drop_if_exists unique_index(:providers, [:name], name: "providers_unique_name_index")

    alter table(:providers) do
      remove :encrypted_credentials
      remove :updated_at
      remove :inserted_at
      remove :retired_at
      remove :checked_at
      remove :check_message
      remove :check_category
      remove :check_status
      remove :checked_revision
      remove :enabled
      remove :revision
      remove :configuration
      remove :adapter_type
      remove :kind
      remove :name
    end

    drop constraint(:ai_usage_role_assignments, "ai_usage_role_assignments_provider_id_fkey")

    alter table(:ai_usage_role_assignments) do
      modify :provider_id, :uuid
    end

    drop constraint(:inventory_imports, "inventory_imports_created_by_id_fkey")

    drop constraint(:inventory_imports, "inventory_imports_provider_id_fkey")

    alter table(:inventory_imports) do
      modify :provider_id, :uuid
    end

    drop constraint(:access_methods, "access_methods_provider_id_fkey")

    drop constraint(:access_methods, "access_methods_target_id_fkey")

    alter table(:access_methods) do
      modify :provider_id, :uuid
    end

    drop constraint(:deliveries, "deliveries_provider_id_fkey")

    drop constraint(:deliveries, "deliveries_report_id_fkey")

    alter table(:deliveries) do
      modify :provider_id, :uuid
    end

    alter table(:verification_attempts) do
      modify :provider_id, :uuid
    end

    drop constraint(:review_decisions, "review_decisions_assignment_id_fkey")

    drop constraint(:review_decisions, "review_decisions_provider_id_fkey")

    drop constraint(:review_decisions, "review_decisions_resolution_run_id_fkey")

    drop constraint(:review_decisions, "review_decisions_case_id_fkey")

    drop constraint(:review_decisions, "review_decisions_proposal_id_fkey")

    alter table(:review_decisions) do
      modify :provider_id, :uuid
    end

    drop constraint(:signal_receipts, "signal_receipts_provider_id_fkey")

    alter table(:signal_receipts) do
      modify :provider_id, :uuid
    end

    drop constraint(:proposals, "proposals_provider_id_fkey")

    drop constraint(:proposals, "proposals_access_method_id_fkey")

    drop constraint(:proposals, "proposals_target_id_fkey")

    drop constraint(:proposals, "proposals_proposed_for_id_fkey")

    drop constraint(:proposals, "proposals_source_turn_id_fkey")

    drop constraint(:proposals, "proposals_resolution_run_id_fkey")

    drop constraint(:proposals, "proposals_case_id_fkey")

    alter table(:proposals) do
      modify :provider_id, :uuid
    end

    drop constraint(:signal_correlations, "signal_correlations_latest_signal_event_id_fkey")

    drop constraint(:signal_correlations, "signal_correlations_provider_id_fkey")

    alter table(:signal_correlations) do
      modify :provider_id, :uuid
    end

    drop table(:providers)

    drop_if_exists unique_index(:ai_usage_role_assignments, [:provider_id, :role],
                     name: "ai_usage_role_assignments_unique_provider_role_index"
                   )

    alter table(:ai_usage_role_assignments) do
      remove :provider_id
      remove :updated_at
      remove :inserted_at
      remove :revision
      remove :enabled
      remove :priority
      remove :role
    end

    alter table(:review_decisions) do
      modify :assignment_id, :uuid
    end

    drop table(:ai_usage_role_assignments)

    drop_if_exists index(:inventory_imports, [:created_by_id])

    drop_if_exists index(:inventory_imports, [:provider_id])

    alter table(:inventory_imports) do
      remove :created_by_id
      remove :provider_id
      remove :updated_at
      remove :inserted_at
      remove :applied_at
      remove :revision
      remove :error_count
      remove :row_count
      remove :content_digest
      remove :source_version
      remove :snapshot_status
      remove :status
      remove :source
      remove :source_type
    end

    drop constraint(:inventory_import_rows, "inventory_import_rows_target_id_fkey")

    drop constraint(:inventory_import_rows, "inventory_import_rows_inventory_import_id_fkey")

    alter table(:inventory_import_rows) do
      modify :inventory_import_id, :uuid
    end

    drop table(:inventory_imports)

    drop_if_exists index(:access_methods, [:provider_id])

    drop_if_exists index(:access_methods, [:target_id])

    alter table(:access_methods) do
      remove :provider_id
    end

    drop_if_exists unique_index(:access_methods, [:target_id, :name],
                     name: "access_methods_unique_target_name_index"
                   )

    alter table(:access_methods) do
      remove :target_id
      remove :updated_at
      remove :inserted_at
      remove :revision
      remove :active
      remove :capabilities
      remove :priority
      remove :provider_revision
      remove :endpoint
      remove :method
      remove :name
    end

    alter table(:verification_attempts) do
      modify :access_method_id, :uuid
    end

    alter table(:proposals) do
      modify :access_method_id, :uuid
    end

    drop table(:access_methods)

    drop_if_exists index(:evidences, [:turn_id])

    drop_if_exists index(:evidences, [:resolution_run_id])

    drop_if_exists index(:evidences, [:case_id])

    drop constraint(:evidences, "evidences_turn_id_fkey")

    drop constraint(:evidences, "evidences_resolution_run_id_fkey")

    drop constraint(:evidences, "evidences_case_id_fkey")

    alter table(:evidences) do
      remove :turn_id
      remove :resolution_run_id
    end

    drop_if_exists unique_index(:evidences, [:case_id, :idempotency_key],
                     name: "evidences_unique_idempotency_index"
                   )

    drop table(:evidences)

    drop constraint(:user_identities, "user_identities_user_id_fkey")

    drop_if_exists unique_index(:user_identities, [:strategy, :uid],
                     name: "user_identities_unique_on_strategy_and_uid_index"
                   )

    drop_if_exists unique_index(:user_identities, [:strategy, :user_id],
                     name: "user_identities_one_identity_per_strategy_and_user_index"
                   )

    drop table(:user_identities)

    drop_if_exists index(:reports, [:case_id])

    drop constraint(:reports, "reports_case_id_fkey")

    drop_if_exists unique_index(:reports, [:case_id, :case_revision],
                     name: "reports_unique_case_revision_index"
                   )

    alter table(:reports) do
      remove :case_id
      remove :revision
      remove :generated_at
      remove :content_digest
      remove :content
      remove :outcome
      remove :language
      remove :case_revision
    end

    alter table(:deliveries) do
      modify :report_id, :uuid
    end

    drop table(:reports)

    drop_if_exists index(:deliveries, [:status])

    drop_if_exists index(:deliveries, [:provider_id])

    drop_if_exists index(:deliveries, [:report_id])

    alter table(:deliveries) do
      remove :provider_id
    end

    drop_if_exists unique_index(:deliveries, [:idempotency_key],
                     name: "deliveries_unique_idempotency_index"
                   )

    drop table(:deliveries)

    drop_if_exists index(:case_events, [:actor_id])

    drop_if_exists index(:case_events, [:resolution_run_id])

    drop_if_exists index(:case_events, [:case_id])

    drop constraint(:case_events, "case_events_actor_id_fkey")

    drop constraint(:case_events, "case_events_resolution_run_id_fkey")

    drop constraint(:case_events, "case_events_case_id_fkey")

    alter table(:case_events) do
      remove :actor_id
      remove :resolution_run_id
    end

    drop_if_exists unique_index(:case_events, [:case_id, :idempotency_key],
                     name: "case_events_unique_idempotency_index"
                   )

    drop table(:case_events)

    drop_if_exists index(:cases, [:current_owner_id])

    drop_if_exists index(:cases, [:selected_target_id])

    drop_if_exists index(:cases, [:initial_target_id])

    drop_if_exists index(:cases, [:split_parent_id])

    drop_if_exists index(:cases, [:authority_setting_id])

    drop_if_exists constraint(:cases, :cases_selected_target_pair)

    drop constraint(:cases, "cases_current_owner_id_fkey")

    drop constraint(:cases, "cases_selected_target_id_fkey")

    drop constraint(:cases, "cases_initial_target_id_fkey")

    drop constraint(:cases, "cases_authority_setting_id_fkey")

    drop constraint(:cases, "cases_split_parent_id_fkey")

    drop_if_exists unique_index(:cases, [:trigger_kind, :source, :source_ref],
                     name: "cases_unique_trigger_index"
                   )

    drop_if_exists unique_index(:cases, [:trigger_kind, :source, :source_ref],
                     name: "cases_one_active_signal_trigger_index"
                   )

    alter table(:cases) do
      remove :current_owner_id
      remove :selected_target_id
      remove :initial_target_id
      remove :authority_setting_id
      remove :split_parent_id
      remove :updated_at
      remove :inserted_at
      remove :selected_target_revision
      remove :revision
      remove :recovery_baseline_at
      remove :resolved_at
      remove :required_human_input
      remove :pending_intent
      remove :stop_reason
      remove :cancel_requested
      remove :max_no_progress_turns
      remove :max_ai_usage_units
      remove :max_related_targets
      remove :max_effects
      remove :max_target_requests
      remove :max_resolver_turns
      remove :max_elapsed_seconds
      remove :authority_mode
      remove :authority_setting_revision
      remove :initial_context
      remove :status
      remove :report_language
      remove :severity
      remove :title
      remove :source_ref
      remove :source
      remove :trigger_kind
    end

    drop constraint(:signal_events, "signal_events_target_id_fkey")

    drop constraint(:signal_events, "signal_events_case_id_fkey")

    drop constraint(:signal_events, "signal_events_condition_id_fkey")

    drop constraint(:signal_events, "signal_events_signal_correlation_id_fkey")

    drop constraint(:signal_events, "signal_events_signal_receipt_id_fkey")

    alter table(:signal_events) do
      modify :case_id, :uuid
    end

    alter table(:verification_attempts) do
      modify :case_id, :uuid
    end

    alter table(:review_decisions) do
      modify :case_id, :uuid
    end

    alter table(:proposals) do
      modify :case_id, :uuid
    end

    drop_if_exists constraint(:audit_runs, :audit_runs_case_pair)

    drop_if_exists constraint(:audit_runs, :audit_runs_target_pair)

    drop constraint(:audit_runs, "audit_runs_case_id_fkey")

    drop constraint(:audit_runs, "audit_runs_target_id_fkey")

    drop constraint(:audit_runs, "audit_runs_audit_schedule_id_fkey")

    alter table(:audit_runs) do
      modify :case_id, :uuid
    end

    drop_if_exists index(:case_condition_memberships, [:case_id])

    drop_if_exists index(:case_condition_memberships, [:condition_id],
                     name: "case_condition_one_active_owner"
                   )

    drop constraint(:case_condition_memberships, "case_condition_memberships_condition_id_fkey")

    drop constraint(:case_condition_memberships, "case_condition_memberships_case_id_fkey")

    alter table(:case_condition_memberships) do
      modify :case_id, :uuid
    end

    drop constraint(:approvals, "approvals_actor_id_fkey")

    drop constraint(:approvals, "approvals_resolution_run_id_fkey")

    drop constraint(:approvals, "approvals_case_id_fkey")

    drop constraint(:approvals, "approvals_proposal_id_fkey")

    alter table(:approvals) do
      modify :case_id, :uuid
    end

    drop constraint(:case_dispatches, "case_dispatches_anchor_target_id_fkey")

    drop constraint(:case_dispatches, "case_dispatches_case_id_fkey")

    alter table(:case_dispatches) do
      modify :case_id, :uuid
    end

    drop constraint(:resolution_runs, "resolution_runs_resumed_by_id_fkey")

    drop constraint(:resolution_runs, "resolution_runs_case_id_fkey")

    drop_if_exists unique_index(:resolution_runs, [:case_id],
                     name: "resolution_runs_one_active_run_index"
                   )

    alter table(:resolution_runs) do
      modify :case_id, :uuid
    end

    drop constraint(:turns, "turns_resolution_run_id_fkey")

    drop constraint(:turns, "turns_case_id_fkey")

    drop_if_exists unique_index(:turns, [:resolution_run_id],
                     name: "turns_one_started_turn_index"
                   )

    alter table(:turns) do
      modify :case_id, :uuid
    end

    drop table(:cases)

    drop_if_exists unique_index(:oidc_providers, [:singleton],
                     name: "oidc_providers_one_oidc_provider_index"
                   )

    drop table(:oidc_providers)

    drop_if_exists index(:signal_events, [:target_id])

    drop_if_exists index(:signal_events, [:case_id])

    drop_if_exists index(:signal_events, [:condition_id])

    drop_if_exists index(:signal_events, [:signal_correlation_id])

    drop_if_exists index(:signal_events, [:signal_receipt_id])

    alter table(:signal_events) do
      remove :target_id
      remove :case_id
      remove :condition_id
    end

    drop_if_exists unique_index(:signal_events, [:signal_receipt_id, :signal_correlation_id],
                     name: "signal_events_unique_receipt_event_index"
                   )

    alter table(:signal_events) do
      remove :signal_correlation_id
      remove :signal_receipt_id
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :attributes
      remove :target_ref
      remove :occurred_at
      remove :source_sequence
      remove :state
      remove :event_key
    end

    alter table(:signal_correlations) do
      modify :latest_signal_event_id, :uuid
    end

    drop table(:signal_events)

    drop table(:tokens)

    drop_if_exists index(:verification_attempts, [:target_id])

    drop_if_exists index(:verification_attempts, [:resolution_run_id])

    drop_if_exists index(:verification_attempts, [:case_id])

    alter table(:verification_attempts) do
      remove :provider_id
      remove :access_method_id
      remove :target_id
      remove :actor_id
      remove :proposal_id
    end

    drop_if_exists unique_index(:verification_attempts, [:operation_id],
                     name: "verification_attempts_unique_operation_index"
                   )

    drop table(:verification_attempts)

    drop_if_exists index(:authority_settings, [:changed_by_id])

    drop constraint(:authority_settings, "authority_settings_changed_by_id_fkey")

    drop_if_exists unique_index(:authority_settings, [:scope],
                     name: "authority_settings_one_current_index"
                   )

    drop_if_exists unique_index(:authority_settings, [:scope, :setting_revision],
                     name: "authority_settings_unique_setting_revision_index"
                   )

    drop table(:authority_settings)

    drop_if_exists index(:review_decisions, [:assignment_id])

    drop_if_exists index(:review_decisions, [:provider_id])

    drop_if_exists index(:review_decisions, [:resolution_run_id])

    drop_if_exists index(:review_decisions, [:case_id])

    alter table(:review_decisions) do
      remove :assignment_id
      remove :provider_id
      remove :resolution_run_id
      remove :case_id
    end

    drop_if_exists unique_index(:review_decisions, [:proposal_id],
                     name: "review_decisions_unique_proposal_index"
                   )

    drop table(:review_decisions)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop_if_exists unique_index(:users, [:bootstrap_marker],
                     name: "users_single_bootstrap_admin_index"
                   )

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :bootstrap_marker
      remove :preferred_language
      remove :role_version
      remove :role
      remove :hashed_password
      remove :email
    end

    drop constraint(:oidc_requests, "oidc_requests_user_id_fkey")

    alter table(:oidc_requests) do
      modify :user_id, :uuid
    end

    alter table(:proposals) do
      modify :proposed_for_id, :uuid
    end

    alter table(:approvals) do
      modify :actor_id, :uuid
    end

    drop constraint(:report_settings, "report_settings_changed_by_id_fkey")

    alter table(:report_settings) do
      modify :changed_by_id, :uuid
    end

    alter table(:resolution_runs) do
      modify :resumed_by_id, :uuid
    end

    drop table(:users)

    drop_if_exists index(:signal_receipts, [:source])

    drop_if_exists index(:signal_receipts, [:provider_id])

    drop_if_exists unique_index(:signal_receipts, [:provider_id, :receipt_id],
                     name: "signal_receipts_unique_source_receipt_index"
                   )

    drop table(:signal_receipts)

    drop_if_exists index(:external_identities, [:target_id])

    drop constraint(:external_identities, "external_identities_target_id_fkey")

    drop_if_exists unique_index(:external_identities, [:source, :kind, :value],
                     name: "external_identities_unique_source_identity_index"
                   )

    drop table(:external_identities)

    drop_if_exists index(:conditions, [:subject_key, :predicate])

    drop_if_exists index(:conditions, [:target_id])

    drop_if_exists index(:conditions, [:signal_correlation_id, :subject_key, :predicate],
                     name: "conditions_one_firing_subject"
                   )

    drop constraint(:conditions, "conditions_target_id_fkey")

    drop constraint(:conditions, "conditions_signal_correlation_id_fkey")

    alter table(:conditions) do
      remove :target_id
    end

    drop_if_exists unique_index(:conditions, [:signal_correlation_id, :occurrence],
                     name: "conditions_unique_occurrence_index"
                   )

    alter table(:conditions) do
      remove :signal_correlation_id
      remove :updated_at
      remove :inserted_at
      remove :revision
      remove :current_source_sequence
      remove :current_occurred_at
      remove :first_fired_at
      remove :state
      remove :subject_ref
      remove :subject_key
      remove :predicate
      remove :occurrence
    end

    alter table(:case_condition_memberships) do
      modify :condition_id, :uuid
    end

    drop table(:conditions)

    drop_if_exists index(:audit_schedules, [:active, :next_run_at])

    drop_if_exists index(:audit_schedules, [:management_boundary_id])

    drop_if_exists constraint(:audit_schedules, :audit_schedules_one_scope)

    drop constraint(:audit_schedules, "audit_schedules_management_boundary_id_fkey")

    drop_if_exists unique_index(:audit_schedules, [:name],
                     name: "audit_schedules_unique_name_index"
                   )

    alter table(:audit_schedules) do
      remove :management_boundary_id
      remove :updated_at
      remove :inserted_at
      remove :revision
      remove :next_run_at
      remove :active
      remove :target_ids
      remove :report_language
      remove :cron_expression
      remove :timezone
      remove :objective
      remove :name
    end

    alter table(:audit_runs) do
      modify :audit_schedule_id, :uuid
    end

    drop table(:audit_schedules)

    drop table(:oidc_requests)

    drop_if_exists index(:proposals, [:proposed_for_id])

    drop_if_exists index(:proposals, [:target_id])

    drop_if_exists index(:proposals, [:resolution_run_id])

    drop_if_exists index(:proposals, [:case_id])

    alter table(:proposals) do
      remove :provider_id
      remove :access_method_id
      remove :target_id
      remove :proposed_for_id
    end

    drop_if_exists unique_index(:proposals, [:source_turn_id],
                     name: "proposals_unique_source_turn_index"
                   )

    alter table(:proposals) do
      remove :source_turn_id
      remove :resolution_run_id
    end

    drop_if_exists unique_index(:proposals, [:reserved_operation_id],
                     name: "proposals_unique_reserved_operation_index"
                   )

    alter table(:proposals) do
      remove :case_id
      remove :updated_at
      remove :inserted_at
      remove :revision
      remove :expires_at
      remove :proposal_digest
      remove :preflight_reason
      remove :preflight_context
      remove :preflight_status
      remove :operation_idempotency_key
      remove :reserved_operation_id
      remove :resolver_identity
      remove :verification_tool
      remove :verification_intent
      remove :expected_result
      remove :affected_conditions
      remove :evidence_ids
      remove :reason
      remove :parameters
      remove :selectors
      remove :operation
      remove :capability
      remove :tool_id
      remove :request_kind
      remove :provider_revision
      remove :access_method_revision
      remove :target_revision
      remove :case_generation
      remove :authority_mode
      remove :status
    end

    alter table(:approvals) do
      modify :proposal_id, :uuid
    end

    drop table(:proposals)

    drop_if_exists index(:audit_runs, [:status])

    drop_if_exists index(:audit_runs, [:case_id])

    drop_if_exists index(:audit_runs, [:target_id])

    drop_if_exists index(:audit_runs, [:audit_schedule_id])

    alter table(:audit_runs) do
      remove :case_id
      remove :target_id
    end

    drop_if_exists unique_index(:audit_runs, [:audit_schedule_id, :scheduled_for, :target_key],
                     name: "audit_runs_unique_occurrence_target_index"
                   )

    drop table(:audit_runs)

    drop table(:case_condition_memberships)

    drop_if_exists index(:approvals, [:actor_id])

    drop_if_exists index(:approvals, [:resolution_run_id])

    drop_if_exists index(:approvals, [:case_id])

    alter table(:approvals) do
      remove :actor_id
      remove :resolution_run_id
      remove :case_id
    end

    drop_if_exists unique_index(:approvals, [:proposal_id],
                     name: "approvals_unique_proposal_index"
                   )

    drop table(:approvals)

    alter table(:case_dispatches) do
      remove :anchor_target_id
    end

    drop_if_exists unique_index(:case_dispatches, [:case_id],
                     name: "case_dispatches_one_dispatch_per_case_index"
                   )

    drop table(:case_dispatches)

    drop_if_exists unique_index(:report_settings, [:scope],
                     name: "report_settings_unique_scope_index"
                   )

    drop table(:report_settings)

    drop_if_exists index(:inventory_import_rows, [:target_id])

    drop_if_exists index(:inventory_import_rows, [:inventory_import_id])

    alter table(:inventory_import_rows) do
      remove :target_id
    end

    drop_if_exists unique_index(:inventory_import_rows, [:inventory_import_id, :position],
                     name: "inventory_import_rows_unique_import_position_index"
                   )

    drop table(:inventory_import_rows)

    drop_if_exists unique_index(:management_boundaries, [:name],
                     name: "management_boundaries_unique_name_index"
                   )

    alter table(:management_boundaries) do
      remove :updated_at
      remove :inserted_at
      remove :revision
      remove :active
      remove :facts
      remove :kind
      remove :name
    end

    drop constraint(:targets, "targets_management_boundary_id_fkey")

    alter table(:targets) do
      modify :management_boundary_id, :uuid
    end

    drop table(:management_boundaries)

    drop_if_exists index(:resolution_runs, [:resumed_by_id])

    alter table(:resolution_runs) do
      remove :resumed_by_id
    end

    drop_if_exists unique_index(:resolution_runs, [:case_id, :generation],
                     name: "resolution_runs_unique_generation_index"
                   )

    alter table(:resolution_runs) do
      remove :case_id
      remove :updated_at
      remove :inserted_at
      remove :revision
      remove :resume_reason
      remove :ended_at
      remove :deadline_at
      remove :started_at
      remove :no_progress_turns
      remove :ai_usage_units
      remove :related_target_count
      remove :effect_count
      remove :target_request_count
      remove :turn_count
      remove :max_no_progress_turns
      remove :max_ai_usage_units
      remove :max_related_targets
      remove :max_effects
      remove :max_target_requests
      remove :max_resolver_turns
      remove :max_elapsed_seconds
      remove :authority_mode
      remove :status
      remove :active
      remove :generation
    end

    alter table(:turns) do
      modify :resolution_run_id, :uuid
    end

    drop table(:resolution_runs)

    drop_if_exists index(:targets, [:management_boundary_id])

    alter table(:targets) do
      remove :management_boundary_id
      remove :updated_at
      remove :inserted_at
      remove :revision
      remove :active
      remove :search_text
      remove :operating_instructions
      remove :facts
      remove :type_id
      remove :kind
      remove :name
    end

    drop constraint(:relationships, "relationships_destination_target_id_fkey")

    drop constraint(:relationships, "relationships_source_target_id_fkey")

    alter table(:relationships) do
      modify :destination_target_id, :uuid
      modify :source_target_id, :uuid
    end

    drop table(:targets)

    drop_if_exists index(:signal_correlations, [:latest_signal_event_id])

    drop_if_exists index(:signal_correlations, [:provider_id])

    alter table(:signal_correlations) do
      remove :latest_signal_event_id
    end

    drop_if_exists unique_index(:signal_correlations, [:provider_id, :source, :event_key],
                     name: "signal_correlations_unique_source_event_index"
                   )

    drop table(:signal_correlations)

    drop_if_exists index(:turns, [:resolution_run_id])

    drop_if_exists index(:turns, [:case_id])

    drop_if_exists unique_index(:turns, [:resolution_run_id, :ordinal],
                     name: "turns_unique_ordinal_index"
                   )

    drop_if_exists unique_index(:turns, [:resolution_run_id, :idempotency_key],
                     name: "turns_unique_idempotency_index"
                   )

    drop table(:turns)

    drop_if_exists index(:relationships, [:destination_target_id])

    drop_if_exists index(:relationships, [:source_target_id])

    drop_if_exists unique_index(
                     :relationships,
                     [:source_target_id, :destination_target_id, :kind],
                     name: "relationships_unique_typed_edge_index"
                   )

    drop table(:relationships)
  end
end
