defmodule Opsonde.Repo.Migrations.ReportSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:report_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :scope, :text, null: false, default: "global"
      add :automatic_case_reports_enabled, :boolean, null: false, default: true
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :changed_by_id,
          references(:users,
            column: :id,
            name: "report_settings_changed_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:report_settings, [:scope], name: "report_settings_unique_scope_index")

    execute "INSERT INTO report_settings (scope, automatic_case_reports_enabled) VALUES ('global', TRUE)"
  end

  def down do
    drop constraint(:report_settings, "report_settings_changed_by_id_fkey")

    drop_if_exists unique_index(:report_settings, [:scope],
                     name: "report_settings_unique_scope_index"
                   )

    drop table(:report_settings)
  end
end
