defmodule Opsonde.Repo.Migrations.ProposalAffectedConditions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:proposals) do
      add :affected_conditions, {:array, :map}, null: false, default: []
    end
  end

  def down do
    alter table(:proposals) do
      remove :affected_conditions
    end
  end
end
