defmodule Opsonde.Repo.Migrations.AuthoritySettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:authority_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :scope, :text, null: false, default: "global"
      add :authority_mode, :text, null: false
      add :signal_automation_enabled, :boolean, null: false
      add :max_elapsed_seconds, :bigint, null: false
      add :max_resolver_turns, :bigint, null: false
      add :max_target_requests, :bigint, null: false
      add :max_effects, :bigint, null: false
      add :max_related_targets, :bigint, null: false
      add :max_ai_usage_units, :bigint, null: false
      add :max_no_progress_turns, :bigint, null: false
      add :setting_revision, :bigint, null: false
      add :active, :boolean, null: false
      add :reason, :text, null: false
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :changed_by_id,
          references(:users,
            column: :id,
            name: "authority_settings_changed_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:authority_settings, [:scope, :setting_revision],
             name: "authority_settings_unique_setting_revision_index"
           )

    create unique_index(:authority_settings, [:scope],
             name: "authority_settings_one_current_index",
             where: "(active = TRUE)"
           )

    create index(:authority_settings, [:changed_by_id])

    execute """
    INSERT INTO authority_settings (
      authority_mode,
      signal_automation_enabled,
      max_elapsed_seconds,
      max_resolver_turns,
      max_target_requests,
      max_effects,
      max_related_targets,
      max_ai_usage_units,
      max_no_progress_turns,
      setting_revision,
      active,
      reason
    ) VALUES (
      'readonly',
      FALSE,
      3600,
      20,
      100,
      10,
      20,
      1000000,
      3,
      1,
      TRUE,
      'system bootstrap'
    )
    """
  end

  def down do
    drop_if_exists index(:authority_settings, [:changed_by_id])

    drop constraint(:authority_settings, "authority_settings_changed_by_id_fkey")

    drop_if_exists unique_index(:authority_settings, [:scope],
                     name: "authority_settings_one_current_index"
                   )

    drop_if_exists unique_index(:authority_settings, [:scope, :setting_revision],
                     name: "authority_settings_unique_setting_revision_index"
                   )

    drop table(:authority_settings)
  end
end
