defmodule Opsonde.Repo.Migrations.AccountPreferredLanguage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :preferred_language, :text, null: false, default: "en"
    end
  end

  def down do
    alter table(:users) do
      remove :preferred_language
    end
  end
end
