defmodule Opsonde.Repo.Migrations.VerificationAttempts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:verification_attempts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false
      add :case_generation, :bigint, null: false
      add :authority_mode, :text, null: false
      add :actor_role_version, :bigint, null: false
      add :target_revision, :bigint, null: false
      add :access_method_revision, :bigint, null: false
      add :provider_revision, :bigint, null: false
      add :tool_id, :text, null: false
      add :capability, :text, null: false
      add :operation, :text, null: false
      add :selectors, :map, null: false
      add :parameters, :map, null: false
      add :expected, :map, null: false
      add :operation_reference, :text
      add :authorization_digest, :text, null: false
      add :policy_context, :map, null: false
      add :accepted_at, :utc_datetime_usec, null: false
      add :dispatch_started_at, :utc_datetime_usec
      add :outcome_category, :text
      add :facts, :map, null: false, default: %{}
      add :provider_evidence, :map, null: false, default: %{}
      add :observed_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "verification_attempts_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :resolution_run_id,
          references(:resolution_runs,
            column: :id,
            name: "verification_attempts_resolution_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :operation_id,
          references(:operations,
            column: :id,
            name: "verification_attempts_operation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:verification_attempts, [:operation_id],
             name: "verification_attempts_unique_operation_index"
           )

    alter table(:verification_attempts) do
      add :proposal_id,
          references(:proposals,
            column: :id,
            name: "verification_attempts_proposal_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :actor_id,
          references(:users,
            column: :id,
            name: "verification_attempts_actor_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :target_id,
          references(:targets,
            column: :id,
            name: "verification_attempts_target_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :access_method_id,
          references(:access_methods,
            column: :id,
            name: "verification_attempts_access_method_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :provider_id,
          references(:providers,
            column: :id,
            name: "verification_attempts_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:verification_attempts, [:case_id])

    create index(:verification_attempts, [:resolution_run_id])

    create index(:verification_attempts, [:target_id])
  end

  def down do
    drop_if_exists index(:verification_attempts, [:target_id])

    drop_if_exists index(:verification_attempts, [:resolution_run_id])

    drop_if_exists index(:verification_attempts, [:case_id])

    drop constraint(:verification_attempts, "verification_attempts_provider_id_fkey")

    drop constraint(:verification_attempts, "verification_attempts_access_method_id_fkey")

    drop constraint(:verification_attempts, "verification_attempts_target_id_fkey")

    drop constraint(:verification_attempts, "verification_attempts_actor_id_fkey")

    drop constraint(:verification_attempts, "verification_attempts_proposal_id_fkey")

    drop constraint(:verification_attempts, "verification_attempts_operation_id_fkey")

    drop constraint(:verification_attempts, "verification_attempts_resolution_run_id_fkey")

    drop constraint(:verification_attempts, "verification_attempts_case_id_fkey")

    alter table(:verification_attempts) do
      remove :provider_id
      remove :access_method_id
      remove :target_id
      remove :actor_id
      remove :proposal_id
    end

    drop_if_exists unique_index(:verification_attempts, [:operation_id],
                     name: "verification_attempts_unique_operation_index"
                   )

    drop table(:verification_attempts)
  end
end
