defmodule Opsonde.Repo.Migrations.AiInvocationDiagnostics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ai_invocations) do
      add :cached_tokens, :bigint
      add :reasoning_tokens, :bigint
      add :finish_reason, :text
      add :failure_code, :text
    end
  end

  def down do
    alter table(:ai_invocations) do
      remove :failure_code
      remove :finish_reason
      remove :reasoning_tokens
      remove :cached_tokens
    end
  end
end
