defmodule Opsonde.Repo.Migrations.SignalIngress do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:signal_correlations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source, :text, null: false
      add :event_key, :text, null: false
      add :current_state, :text, null: false, default: "pending"
      add :current_occurred_at, :utc_datetime_usec
      add :current_source_sequence, :text
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :provider_id,
          references(:providers,
            column: :id,
            name: "signal_correlations_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:signal_correlations, [:provider_id, :source, :event_key],
             name: "signal_correlations_unique_source_event_index"
           )

    alter table(:signal_correlations) do
      add :latest_signal_event_id, :uuid

      add :case_id,
          references(:cases,
            column: :id,
            name: "signal_correlations_case_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:signal_correlations, [:provider_id])

    create index(:signal_correlations, [:case_id])

    create index(:signal_correlations, [:latest_signal_event_id])

    create table(:signal_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:signal_correlations) do
      modify :latest_signal_event_id,
             references(:signal_events,
               column: :id,
               name: "signal_correlations_latest_signal_event_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:signal_events) do
      add :event_key, :text, null: false
      add :state, :text, null: false
      add :source_sequence, :text
      add :occurred_at, :utc_datetime_usec, null: false
      add :target_ref, :map
      add :attributes, :map, null: false, default: %{}
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :signal_receipt_id, :uuid, null: false

      add :signal_correlation_id,
          references(:signal_correlations,
            column: :id,
            name: "signal_events_signal_correlation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:signal_events, [:signal_receipt_id, :signal_correlation_id],
             name: "signal_events_unique_receipt_event_index"
           )

    alter table(:signal_events) do
      add :case_id,
          references(:cases,
            column: :id,
            name: "signal_events_case_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :target_id,
          references(:targets,
            column: :id,
            name: "signal_events_target_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:signal_events, [:signal_receipt_id])

    create index(:signal_events, [:signal_correlation_id])

    create index(:signal_events, [:case_id])

    create index(:signal_events, [:target_id])

    create table(:signal_receipts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:signal_events) do
      modify :signal_receipt_id,
             references(:signal_receipts,
               column: :id,
               name: "signal_events_signal_receipt_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:signal_receipts) do
      add :provider_revision, :bigint, null: false
      add :receipt_id, :text, null: false
      add :source, :text, null: false
      add :received_at, :utc_datetime_usec, null: false
      add :metadata, :map, null: false, default: %{}
      add :normalized_digest, :text, null: false
      add :event_count, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :provider_id,
          references(:providers,
            column: :id,
            name: "signal_receipts_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:signal_receipts, [:provider_id, :receipt_id],
             name: "signal_receipts_unique_source_receipt_index"
           )

    create index(:signal_receipts, [:provider_id])

    create index(:signal_receipts, [:source])

    create unique_index(:turns, [:resolution_run_id],
             name: "turns_one_started_turn_index",
             where: "(status = 'started')"
           )
  end

  def down do
    drop_if_exists unique_index(:turns, [:resolution_run_id],
                     name: "turns_one_started_turn_index"
                   )

    drop_if_exists index(:signal_receipts, [:source])

    drop_if_exists index(:signal_receipts, [:provider_id])

    drop constraint(:signal_receipts, "signal_receipts_provider_id_fkey")

    drop_if_exists unique_index(:signal_receipts, [:provider_id, :receipt_id],
                     name: "signal_receipts_unique_source_receipt_index"
                   )

    alter table(:signal_receipts) do
      remove :provider_id
      remove :updated_at
      remove :inserted_at
      remove :event_count
      remove :normalized_digest
      remove :metadata
      remove :received_at
      remove :source
      remove :receipt_id
      remove :provider_revision
    end

    drop constraint(:signal_events, "signal_events_target_id_fkey")

    drop constraint(:signal_events, "signal_events_case_id_fkey")

    drop constraint(:signal_events, "signal_events_signal_correlation_id_fkey")

    drop constraint(:signal_events, "signal_events_signal_receipt_id_fkey")

    alter table(:signal_events) do
      modify :signal_receipt_id, :uuid
    end

    drop table(:signal_receipts)

    drop_if_exists index(:signal_events, [:target_id])

    drop_if_exists index(:signal_events, [:case_id])

    drop_if_exists index(:signal_events, [:signal_correlation_id])

    drop_if_exists index(:signal_events, [:signal_receipt_id])

    alter table(:signal_events) do
      remove :target_id
      remove :case_id
    end

    drop_if_exists unique_index(:signal_events, [:signal_receipt_id, :signal_correlation_id],
                     name: "signal_events_unique_receipt_event_index"
                   )

    alter table(:signal_events) do
      remove :signal_correlation_id
      remove :signal_receipt_id
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :attributes
      remove :target_ref
      remove :occurred_at
      remove :source_sequence
      remove :state
      remove :event_key
    end

    drop constraint(:signal_correlations, "signal_correlations_case_id_fkey")

    drop constraint(:signal_correlations, "signal_correlations_latest_signal_event_id_fkey")

    drop constraint(:signal_correlations, "signal_correlations_provider_id_fkey")

    alter table(:signal_correlations) do
      modify :latest_signal_event_id, :uuid
    end

    drop table(:signal_events)

    drop_if_exists index(:signal_correlations, [:latest_signal_event_id])

    drop_if_exists index(:signal_correlations, [:case_id])

    drop_if_exists index(:signal_correlations, [:provider_id])

    alter table(:signal_correlations) do
      remove :case_id
      remove :latest_signal_event_id
    end

    drop_if_exists unique_index(:signal_correlations, [:provider_id, :source, :event_key],
                     name: "signal_correlations_unique_source_event_index"
                   )

    drop table(:signal_correlations)
  end
end
