defmodule Opsonde.Repo.Migrations.AddOidc do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:oidc_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :purpose, :text, null: false
      add :start_token_digest, :binary, null: false
      add :browser_binding_digest, :binary
      add :verifier_digest, :binary
      add :code_digest, :binary
      add :redirect_uri, :text
      add :expires_at, :utc_datetime_usec, null: false
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :consumed_at, :utc_datetime_usec
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "oidc_requests_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:oidc_providers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :issuer, :text, null: false
      add :client_id, :text, null: false
      add :id_token_alg, :text, null: false, default: "RS256"
      add :enabled, :boolean, null: false, default: true
      add :revision, :bigint, null: false, default: 1
      add :singleton, :text, null: false, default: "oidc"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :encrypted_client_secret, :binary, null: false
    end

    create unique_index(:oidc_providers, [:singleton],
             name: "oidc_providers_one_oidc_provider_index"
           )

    create table(:user_identities, primary_key: false) do
      add :uid, :text, null: false
      add :strategy, :text, null: false
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "user_identities_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:user_identities, [:strategy, :user_id],
             name: "user_identities_one_identity_per_strategy_and_user_index"
           )

    create unique_index(:user_identities, [:strategy, :uid],
             name: "user_identities_unique_on_strategy_and_uid_index"
           )
  end

  def down do
    drop constraint(:user_identities, "user_identities_user_id_fkey")

    drop_if_exists unique_index(:user_identities, [:strategy, :uid],
                     name: "user_identities_unique_on_strategy_and_uid_index"
                   )

    drop_if_exists unique_index(:user_identities, [:strategy, :user_id],
                     name: "user_identities_one_identity_per_strategy_and_user_index"
                   )

    drop table(:user_identities)

    drop_if_exists unique_index(:oidc_providers, [:singleton],
                     name: "oidc_providers_one_oidc_provider_index"
                   )

    drop table(:oidc_providers)

    drop constraint(:oidc_requests, "oidc_requests_user_id_fkey")

    drop table(:oidc_requests)
  end
end
