defmodule Opsonde.Repo.Migrations.ApprovalAuthority do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:approvals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :decision, :text, null: false
      add :source, :text, null: false
      add :proposal_digest, :text, null: false
      add :proposal_revision, :bigint, null: false
      add :case_generation, :bigint, null: false
      add :actor_role_version, :bigint, null: false
      add :clearance_digest, :text
      add :reason, :text, null: false
      add :decided_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :proposal_id,
          references(:proposals,
            column: :id,
            name: "approvals_proposal_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:approvals, [:proposal_id], name: "approvals_unique_proposal_index")

    alter table(:approvals) do
      add :case_id,
          references(:cases,
            column: :id,
            name: "approvals_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :resolution_run_id,
          references(:resolution_runs,
            column: :id,
            name: "approvals_resolution_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :actor_id,
          references(:users,
            column: :id,
            name: "approvals_actor_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:approvals, [:case_id])

    create index(:approvals, [:resolution_run_id])

    create index(:approvals, [:actor_id])
  end

  def down do
    drop_if_exists index(:approvals, [:actor_id])

    drop_if_exists index(:approvals, [:resolution_run_id])

    drop_if_exists index(:approvals, [:case_id])

    drop constraint(:approvals, "approvals_actor_id_fkey")

    drop constraint(:approvals, "approvals_resolution_run_id_fkey")

    drop constraint(:approvals, "approvals_case_id_fkey")

    drop constraint(:approvals, "approvals_proposal_id_fkey")

    alter table(:approvals) do
      remove :actor_id
      remove :resolution_run_id
      remove :case_id
    end

    drop_if_exists unique_index(:approvals, [:proposal_id],
                     name: "approvals_unique_proposal_index"
                   )

    drop table(:approvals)
  end
end
