defmodule Opsonde.Repo.Migrations.Targets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:access_methods, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :platform, :text, null: false
      add :method, :text, null: false
      add :endpoint, :text, null: false
      add :provider_revision, :bigint, null: false
      add :priority, :bigint, null: false, default: 100
      add :capabilities, {:array, :text}, null: false, default: []
      add :active, :boolean, null: false, default: true
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :target_id, :uuid, null: false
    end

    create unique_index(:access_methods, [:target_id, :name],
             name: "access_methods_unique_target_name_index"
           )

    alter table(:access_methods) do
      add :provider_id,
          references(:providers,
            column: :id,
            name: "access_methods_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:access_methods, [:target_id])

    create index(:access_methods, [:provider_id])

    create table(:external_identities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source, :text, null: false
      add :kind, :text, null: false
      add :value, :text, null: false
      add :search_text, :text, null: false
      add :active, :boolean, null: false, default: true
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :target_id, :uuid, null: false
    end

    create unique_index(:external_identities, [:source, :kind, :value],
             name: "external_identities_unique_source_identity_index"
           )

    create index(:external_identities, [:target_id])

    create table(:management_boundaries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :kind, :text, null: false
      add :facts, :map, null: false, default: %{}
      add :active, :boolean, null: false, default: true
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:management_boundaries, [:name],
             name: "management_boundaries_unique_name_index"
           )

    create table(:relationships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :facts, :map, null: false, default: %{}
      add :search_text, :text, null: false
      add :active, :boolean, null: false, default: true
      add :valid_until, :utc_datetime_usec
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_target_id, :uuid, null: false
      add :destination_target_id, :uuid, null: false
    end

    create unique_index(:relationships, [:source_target_id, :destination_target_id, :kind],
             name: "relationships_unique_typed_edge_index"
           )

    create index(:relationships, [:source_target_id])

    create index(:relationships, [:destination_target_id])

    create table(:targets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:access_methods) do
      modify :target_id,
             references(:targets,
               column: :id,
               name: "access_methods_target_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:external_identities) do
      modify :target_id,
             references(:targets,
               column: :id,
               name: "external_identities_target_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:relationships) do
      modify :source_target_id,
             references(:targets,
               column: :id,
               name: "relationships_source_target_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :destination_target_id,
             references(:targets,
               column: :id,
               name: "relationships_destination_target_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:targets) do
      add :name, :text, null: false
      add :kind, :text, null: false
      add :platform, :text, null: false
      add :facts, :map, null: false, default: %{}
      add :search_text, :text, null: false
      add :active, :boolean, null: false, default: true
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :management_boundary_id,
          references(:management_boundaries,
            column: :id,
            name: "targets_management_boundary_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:targets, [:management_boundary_id])
  end

  def down do
    drop_if_exists index(:targets, [:management_boundary_id])

    drop constraint(:targets, "targets_management_boundary_id_fkey")

    alter table(:targets) do
      remove :management_boundary_id
      remove :updated_at
      remove :inserted_at
      remove :revision
      remove :active
      remove :search_text
      remove :facts
      remove :platform
      remove :kind
      remove :name
    end

    drop constraint(:relationships, "relationships_destination_target_id_fkey")

    drop constraint(:relationships, "relationships_source_target_id_fkey")

    alter table(:relationships) do
      modify :destination_target_id, :uuid
      modify :source_target_id, :uuid
    end

    drop constraint(:external_identities, "external_identities_target_id_fkey")

    alter table(:external_identities) do
      modify :target_id, :uuid
    end

    drop constraint(:access_methods, "access_methods_provider_id_fkey")

    drop constraint(:access_methods, "access_methods_target_id_fkey")

    alter table(:access_methods) do
      modify :target_id, :uuid
    end

    drop table(:targets)

    drop_if_exists index(:relationships, [:destination_target_id])

    drop_if_exists index(:relationships, [:source_target_id])

    drop_if_exists unique_index(
                     :relationships,
                     [:source_target_id, :destination_target_id, :kind],
                     name: "relationships_unique_typed_edge_index"
                   )

    drop table(:relationships)

    drop_if_exists unique_index(:management_boundaries, [:name],
                     name: "management_boundaries_unique_name_index"
                   )

    drop table(:management_boundaries)

    drop_if_exists index(:external_identities, [:target_id])

    drop_if_exists unique_index(:external_identities, [:source, :kind, :value],
                     name: "external_identities_unique_source_identity_index"
                   )

    drop table(:external_identities)

    drop_if_exists index(:access_methods, [:provider_id])

    drop_if_exists index(:access_methods, [:target_id])

    alter table(:access_methods) do
      remove :provider_id
    end

    drop_if_exists unique_index(:access_methods, [:target_id, :name],
                     name: "access_methods_unique_target_name_index"
                   )

    drop table(:access_methods)
  end
end
