defmodule Opsonde.Repo.Migrations.ReviewerDelivery do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:proposals) do
      add :tool_id, :text, null: false
    end

    create table(:review_decisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :outcome, :text, null: false
      add :verdict, :text, null: false
      add :category, :text
      add :reason, :text, null: false
      add :selection_source, :text
      add :provider_revision, :bigint
      add :assignment_revision, :bigint
      add :session_id, :text, null: false
      add :resolver_session_id, :text, null: false
      add :proposal_digest, :text, null: false
      add :input_tokens, :bigint, null: false
      add :output_tokens, :bigint, null: false
      add :result_digest, :text, null: false
      add :decided_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :proposal_id,
          references(:proposals,
            column: :id,
            name: "review_decisions_proposal_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:review_decisions, [:proposal_id],
             name: "review_decisions_unique_proposal_index"
           )

    alter table(:review_decisions) do
      add :case_id,
          references(:cases,
            column: :id,
            name: "review_decisions_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :resolution_run_id,
          references(:resolution_runs,
            column: :id,
            name: "review_decisions_resolution_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :provider_id,
          references(:providers,
            column: :id,
            name: "review_decisions_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :assignment_id,
          references(:ai_usage_role_assignments,
            column: :id,
            name: "review_decisions_assignment_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:review_decisions, [:case_id])

    create index(:review_decisions, [:resolution_run_id])

    create index(:review_decisions, [:provider_id])

    create index(:review_decisions, [:assignment_id])
  end

  def down do
    drop_if_exists index(:review_decisions, [:assignment_id])

    drop_if_exists index(:review_decisions, [:provider_id])

    drop_if_exists index(:review_decisions, [:resolution_run_id])

    drop_if_exists index(:review_decisions, [:case_id])

    drop constraint(:review_decisions, "review_decisions_assignment_id_fkey")

    drop constraint(:review_decisions, "review_decisions_provider_id_fkey")

    drop constraint(:review_decisions, "review_decisions_resolution_run_id_fkey")

    drop constraint(:review_decisions, "review_decisions_case_id_fkey")

    drop constraint(:review_decisions, "review_decisions_proposal_id_fkey")

    alter table(:review_decisions) do
      remove :assignment_id
      remove :provider_id
      remove :resolution_run_id
      remove :case_id
    end

    drop_if_exists unique_index(:review_decisions, [:proposal_id],
                     name: "review_decisions_unique_proposal_index"
                   )

    drop table(:review_decisions)

    alter table(:proposals) do
      remove :tool_id
    end
  end
end
