defmodule Opsonde.Repo.Migrations.TargetPolicies do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:target_policies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :request_kinds, {:array, :text}, null: false
      add :capabilities, {:array, :text}, null: false, default: []
      add :operations, {:array, :text}, null: false, default: []
      add :selector_match, :map, null: false, default: %{}
      add :parameter_match, :map, null: false, default: %{}
      add :reason, :text, null: false
      add :enabled, :boolean, null: false, default: true
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :target_id,
          references(:targets,
            column: :id,
            name: "target_policies_target_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:target_policies, [:target_id, :name],
             name: "target_policies_unique_target_name_index"
           )

    create index(:target_policies, [:target_id])
  end

  def down do
    drop_if_exists index(:target_policies, [:target_id])

    drop constraint(:target_policies, "target_policies_target_id_fkey")

    drop_if_exists unique_index(:target_policies, [:target_id, :name],
                     name: "target_policies_unique_target_name_index"
                   )

    drop table(:target_policies)
  end
end
