defmodule Opsonde.Repo.Migrations.CaseTargetSelection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cases) do
      add :selected_target_revision, :bigint

      add :selected_target_id,
          references(:targets,
            column: :id,
            name: "cases_selected_target_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create constraint(:cases, :cases_selected_target_pair,
             check: """
               (selected_target_id IS NULL AND selected_target_revision IS NULL) OR (selected_target_id IS NOT NULL AND selected_target_revision IS NOT NULL)
             """
           )

    create index(:cases, [:selected_target_id])
  end

  def down do
    drop_if_exists index(:cases, [:selected_target_id])

    drop_if_exists constraint(:cases, :cases_selected_target_pair)

    drop constraint(:cases, "cases_selected_target_id_fkey")

    alter table(:cases) do
      remove :selected_target_id
      remove :selected_target_revision
    end
  end
end
