defmodule Opsonde.Repo.Migrations.CorrelateSignalIncidents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:signal_events) do
      add :incident_key, :text
    end

    alter table(:cases) do
      add :incident_key, :text
    end

    create index(:cases, [:incident_key],
             name: "cases_active_incident_key_index",
             unique: true,
             where: "incident_key IS NOT NULL AND status IN ('running', 'needs_attention')"
           )
  end

  def down do
    drop_if_exists index(:cases, [:incident_key], name: "cases_active_incident_key_index")

    alter table(:cases) do
      remove :incident_key
    end

    alter table(:signal_events) do
      remove :incident_key
    end
  end
end
