defmodule Opsonde.Repo.Migrations.AutonomousTargetRequests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:proposals) do
      add :request_kind, :text, null: false
    end

    alter table(:operations) do
      add :request_kind, :text, null: false
    end
  end

  def down do
    alter table(:operations) do
      remove :request_kind
    end

    alter table(:proposals) do
      remove :request_kind
    end
  end
end
