defmodule Opsonde.Repo.Migrations.RemoveSignalCorrelationCaseOwner do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:signal_correlations) do
      remove :case_id
    end

    drop_if_exists index(:signal_correlations, [:case_id])
  end

  def down do
    alter table(:signal_correlations) do
      add :case_id,
          references(:cases,
            column: :id,
            name: "signal_correlations_case_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:signal_correlations, [:case_id])
  end
end
