defmodule Opsonde.Repo.Migrations.CaseConditionDispatch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:case_dispatches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :state, :text, null: false
      add :first_received_at, :utc_datetime_usec, null: false
      add :due_at, :utc_datetime_usec, null: false
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "case_dispatches_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:case_dispatches, [:case_id],
             name: "case_dispatches_one_dispatch_per_case_index"
           )

    alter table(:case_dispatches) do
      add :anchor_target_id,
          references(:targets,
            column: :id,
            name: "case_dispatches_anchor_target_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:case_condition_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :attached_at, :utc_datetime_usec, null: false
      add :detached_at, :utc_datetime_usec
      add :reason, :text, null: false
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "case_condition_memberships_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :condition_id,
          references(:conditions,
            column: :id,
            name: "case_condition_memberships_condition_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:case_condition_memberships, [:condition_id],
             name: "case_condition_one_active_owner",
             unique: true,
             where: "detached_at IS NULL"
           )

    create index(:case_condition_memberships, [:case_id], where: "detached_at IS NULL")

    drop_if_exists index(:cases, [:incident_key], name: "cases_active_incident_key_index")

    alter table(:signal_events) do
      remove :incident_key
    end

    alter table(:cases) do
      remove :incident_key
    end
  end

  def down do
    alter table(:cases) do
      add :incident_key, :text
    end

    alter table(:signal_events) do
      add :incident_key, :text
    end

    create index(:cases, [:incident_key],
             name: "cases_active_incident_key_index",
             unique: true,
             where: "incident_key IS NOT NULL AND status IN ('running', 'needs_attention')"
           )

    drop_if_exists index(:case_condition_memberships, [:case_id])

    drop_if_exists index(:case_condition_memberships, [:condition_id],
                     name: "case_condition_one_active_owner"
                   )

    drop constraint(:case_condition_memberships, "case_condition_memberships_condition_id_fkey")

    drop constraint(:case_condition_memberships, "case_condition_memberships_case_id_fkey")

    drop table(:case_condition_memberships)

    drop constraint(:case_dispatches, "case_dispatches_anchor_target_id_fkey")

    drop constraint(:case_dispatches, "case_dispatches_case_id_fkey")

    alter table(:case_dispatches) do
      remove :anchor_target_id
    end

    drop_if_exists unique_index(:case_dispatches, [:case_id],
                     name: "case_dispatches_one_dispatch_per_case_index"
                   )

    drop table(:case_dispatches)
  end
end
