defmodule Opsonde.Repo.Migrations.AddBmcSecrets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bmc_operations) do
      add :secret_bindings, :map, null: false, default: %{}
    end

    create table(:bmc_secrets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :active, :boolean, null: false, default: true
      add :revision, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :access_method_id,
          references(:access_methods,
            column: :id,
            name: "bmc_secrets_access_method_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:bmc_secrets, [:access_method_id, :name],
             name: "bmc_secrets_unique_method_name_index"
           )

    alter table(:bmc_secrets) do
      add :encrypted_value, :binary, null: false
    end
  end

  def down do
    drop constraint(:bmc_secrets, "bmc_secrets_access_method_id_fkey")

    alter table(:bmc_secrets) do
      remove :encrypted_value
    end

    drop_if_exists unique_index(:bmc_secrets, [:access_method_id, :name],
                     name: "bmc_secrets_unique_method_name_index"
                   )

    drop table(:bmc_secrets)

    alter table(:bmc_operations) do
      remove :secret_bindings
    end
  end
end
