defmodule Opsonde.Repo.Migrations.NotificationDeliveries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:deliveries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :report_revision, :bigint, null: false
      add :provider_revision, :bigint, null: false
      add :destination_id, :uuid, null: false
      add :destination_revision, :bigint, null: false
      add :idempotency_key, :text, null: false
      add :status, :text, null: false
      add :reference, :text
      add :details, :map, null: false, default: %{}
      add :enqueued_at, :utc_datetime_usec, null: false
      add :dispatch_started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :revision, :bigint, null: false, default: 1

      add :report_id,
          references(:reports,
            column: :id,
            name: "deliveries_report_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:deliveries, [:idempotency_key],
             name: "deliveries_unique_idempotency_index"
           )

    alter table(:deliveries) do
      add :provider_id,
          references(:providers,
            column: :id,
            name: "deliveries_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:deliveries, [:report_id])

    create index(:deliveries, [:provider_id])

    create index(:deliveries, [:status])
  end

  def down do
    drop_if_exists index(:deliveries, [:status])

    drop_if_exists index(:deliveries, [:provider_id])

    drop_if_exists index(:deliveries, [:report_id])

    drop constraint(:deliveries, "deliveries_provider_id_fkey")

    drop constraint(:deliveries, "deliveries_report_id_fkey")

    alter table(:deliveries) do
      remove :provider_id
    end

    drop_if_exists unique_index(:deliveries, [:idempotency_key],
                     name: "deliveries_unique_idempotency_index"
                   )

    drop table(:deliveries)
  end
end
