defmodule Opsonde.Repo.Migrations.OperationStateMachine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:operations) do
      modify :status, :text, default: "queued"
    end
  end

  def down do
    alter table(:operations) do
      modify :status, :text, default: nil
    end
  end
end
