defmodule Opsonde.Repo.Migrations.CaseReports do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :case_revision, :bigint, null: false
      add :language, :text, null: false
      add :outcome, :text, null: false
      add :content, :map, null: false
      add :content_digest, :text, null: false
      add :generated_at, :utc_datetime_usec, null: false
      add :revision, :bigint, null: false, default: 1

      add :case_id,
          references(:cases,
            column: :id,
            name: "reports_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:reports, [:case_id, :case_revision],
             name: "reports_unique_case_revision_index"
           )

    create index(:reports, [:case_id])
  end

  def down do
    drop_if_exists index(:reports, [:case_id])

    drop constraint(:reports, "reports_case_id_fkey")

    drop_if_exists unique_index(:reports, [:case_id, :case_revision],
                     name: "reports_unique_case_revision_index"
                   )

    drop table(:reports)
  end
end
