defmodule Opsonde.Repo.Migrations.OperationResourceScope do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:operations) do
      add :resource_scope, :text, null: false
    end

    create index(:operations, [:target_id, :resource_scope])
  end

  def down do
    drop_if_exists index(:operations, [:target_id, :resource_scope])

    alter table(:operations) do
      remove :resource_scope
    end
  end
end
